package br.com.fisioterapia.application;

import br.com.fisioterapia.database.pessoas.Proprietario;
import br.com.fisioterapia.database.pessoas.Fisioterapeuta;
import br.com.fisioterapia.jframe.atualizar.AtualizarAnamneseJF;
import br.com.fisioterapia.jframe.cadastro.PacienteJF;
import br.com.fisioterapia.jframe.buscar.BuscarProprietarioJF;
import br.com.fisioterapia.jframe.buscar.BuscarPacienteJF;
import br.com.fisioterapia.jframe.buscar.BuscarFisioterapeutaJF;
import br.com.fisioterapia.jframe.buscar.BuscarFichaJF;
import br.com.fisioterapia.jframe.buscar.BuscarExercicioJF;
import br.com.fisioterapia.jframe.buscar.BuscarEquipamentoJF;
import br.com.fisioterapia.jframe.buscar.BuscarConsultaJF;
import br.com.fisioterapia.jframe.buscar.BuscarAnamneseJF;
import br.com.fisioterapia.jframe.atualizar.AtualizarProprietarioJF;
import br.com.fisioterapia.jframe.atualizar.AtualizarPacienteJF;
import br.com.fisioterapia.jframe.atualizar.AtualizarFisioterapeutaJF;
import br.com.fisioterapia.jframe.atualizar.AtualizarExercicioJF;
import br.com.fisioterapia.jframe.atualizar.AtualizarEquipamentoJF;
import br.com.fisioterapia.jframe.atualizar.AtualizarConsultaJF;
import br.com.fisioterapia.jframe.buscar.BuscarConsultasDatasJF;
import br.com.fisioterapia.jframe.cadastro.ConsultaJF;
import br.com.fisioterapia.jframe.cadastro.AnamneseJF;
import br.com.fisioterapia.jframe.cadastro.EquipamentosJF;
import br.com.fisioterapia.jframe.cadastro.ExercicioJF;
import br.com.fisioterapia.jframe.cadastro.FichaJF;
import br.com.fisioterapia.jframe.cadastro.FisioterapeutaJF;
import br.com.fisioterapia.jframe.cadastro.ProprietarioJF;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class janelaPrincipal extends javax.swing.JFrame {

    public BuscarConsultasDatasJF buscarConsultasDatasJF = new BuscarConsultasDatasJF();
    public AtualizarAnamneseJF atualizarAnamneseJF = new AtualizarAnamneseJF();
    public BuscarFichaJF buscarFichaJF = new BuscarFichaJF();
    public FichaJF fichaJF = new FichaJF();
    public BuscarProprietarioJF buscarProprietarioJF = new BuscarProprietarioJF();
    public BuscarFisioterapeutaJF buscarFisioterapeutaJF = new BuscarFisioterapeutaJF();
    public BuscarEquipamentoJF buscarEquipamentoJF = new BuscarEquipamentoJF();
    public BuscarExercicioJF buscarExercicioJF = new BuscarExercicioJF();
    public BuscarConsultaJF buscarConsultaJF = new BuscarConsultaJF();
    public BuscarPacienteJF buscarPacienteJF = new BuscarPacienteJF();
    public AtualizarConsultaJF atualizarConsultaJF = new AtualizarConsultaJF();
    public BuscarAnamneseJF buscarAnamneseJF = new BuscarAnamneseJF();
    public AtualizarPacienteJF atualizarPacienteJF = new AtualizarPacienteJF();
    public AtualizarExercicioJF atualizarExercicioJF = new AtualizarExercicioJF();
    public AtualizarFisioterapeutaJF atualizarFisioterapeutaJF = new AtualizarFisioterapeutaJF();
    public AtualizarProprietarioJF atualizarProprietarioJF = new AtualizarProprietarioJF();
    public AtualizarEquipamentoJF atualizarEquipamentoJF = new AtualizarEquipamentoJF();
    public EquipamentosJF equipamentosJF = new EquipamentosJF();
    public FisioterapeutaJF fisioterapeutaJF = new FisioterapeutaJF();
    public ProprietarioJF proprietarioJF = new ProprietarioJF();
    public AnamneseJF anamneseJF = new AnamneseJF();
    public ExercicioJF exercicioJF = new ExercicioJF();
    public PacienteJF pacienteJF = new PacienteJF();
    public ConsultaJF consultaJF = new ConsultaJF();

    /**
     * Creates new form janelaPrincipal
     */
    public janelaPrincipal() {
        initComponents();
        menuBar.setEnabled(false);
        menuBar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        lblSaida = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuCadastrar = new javax.swing.JMenu();
        mnuCadastrarPaciente = new javax.swing.JMenuItem();
        mnucadastrarAnamnese = new javax.swing.JMenuItem();
        mnuCadastrarConsulta = new javax.swing.JMenuItem();
        mnuCadastrarFicha = new javax.swing.JMenuItem();
        mnuCadastrarExercicio = new javax.swing.JMenuItem();
        mnuCadastrarEquipamentos = new javax.swing.JMenuItem();
        mnuCadastrarFisioterapeuta = new javax.swing.JMenuItem();
        mnuCadastrarProprietario = new javax.swing.JMenuItem();
        mnuAtualizar = new javax.swing.JMenu();
        mnuAtualizarPaciente = new javax.swing.JMenuItem();
        mnuAtualizarAnamnese = new javax.swing.JMenuItem();
        mnuAtualizarConsulta = new javax.swing.JMenuItem();
        mnuAtualizarExercicio = new javax.swing.JMenuItem();
        mnuAtualizarEquipamentos = new javax.swing.JMenuItem();
        mnuAtualizarFisioterapeuta = new javax.swing.JMenuItem();
        mnuAtualizarProprietario = new javax.swing.JMenuItem();
        mnuBuscar = new javax.swing.JMenu();
        mnuBuscarPaciente = new javax.swing.JMenuItem();
        mnuBuscarAnamnese = new javax.swing.JMenuItem();
        mnuBuscarConsulta = new javax.swing.JMenuItem();
        mnuBuscarTodasConsultas = new javax.swing.JMenuItem();
        mnuBuscarFicha = new javax.swing.JMenuItem();
        mnuBuscarExercicio = new javax.swing.JMenuItem();
        mnuBuscarEquipamentos = new javax.swing.JMenuItem();
        mnuBuscarFisioterapeuta = new javax.swing.JMenuItem();
        mnuBuscarProprietario = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenu();
        mnuLogout = new javax.swing.JMenuItem();
        mnuSairPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        desktopPane.setPreferredSize(getMaximumSize());

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login");
        desktopPane.add(lblLogin);
        lblLogin.setBounds(120, 100, 60, 30);

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha");
        desktopPane.add(lblSenha);
        lblSenha.setBounds(120, 140, 60, 30);
        desktopPane.add(txtLogin);
        txtLogin.setBounds(170, 100, 160, 30);

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        desktopPane.add(btnEntrar);
        btnEntrar.setBounds(200, 230, 110, 30);
        desktopPane.add(txtSenha);
        txtSenha.setBounds(170, 140, 160, 30);
        desktopPane.add(lblSaida);
        lblSaida.setBounds(10, 640, 750, 20);

        mnuCadastrar.setMnemonic('f');
        mnuCadastrar.setText("Cadastrar");
        mnuCadastrar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuCadastrarMenuSelected(evt);
            }
        });
        mnuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarActionPerformed(evt);
            }
        });

        mnuCadastrarPaciente.setMnemonic('o');
        mnuCadastrarPaciente.setText("Paciente");
        mnuCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarPacienteActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarPaciente);

        mnucadastrarAnamnese.setMnemonic('a');
        mnucadastrarAnamnese.setText("Anamnese");
        mnucadastrarAnamnese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucadastrarAnamneseActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnucadastrarAnamnese);

        mnuCadastrarConsulta.setMnemonic('x');
        mnuCadastrarConsulta.setText("Consulta");
        mnuCadastrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarConsultaActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarConsulta);

        mnuCadastrarFicha.setText("Ficha");
        mnuCadastrarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarFichaActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarFicha);

        mnuCadastrarExercicio.setMnemonic('s');
        mnuCadastrarExercicio.setText("Exercício");
        mnuCadastrarExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarExercicioActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarExercicio);

        mnuCadastrarEquipamentos.setMnemonic('y');
        mnuCadastrarEquipamentos.setText("Equipamentos");
        mnuCadastrarEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarEquipamentosActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarEquipamentos);

        mnuCadastrarFisioterapeuta.setMnemonic('t');
        mnuCadastrarFisioterapeuta.setText("Fisioterapeuta");
        mnuCadastrarFisioterapeuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarFisioterapeutaActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarFisioterapeuta);

        mnuCadastrarProprietario.setMnemonic('p');
        mnuCadastrarProprietario.setText("Proprietário");
        mnuCadastrarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarProprietarioActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarProprietario);

        menuBar.add(mnuCadastrar);

        mnuAtualizar.setText("Atualizar");
        mnuAtualizar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuAtualizarMenuSelected(evt);
            }
        });

        mnuAtualizarPaciente.setText("Paciente");
        mnuAtualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtualizarPacienteActionPerformed(evt);
            }
        });
        mnuAtualizar.add(mnuAtualizarPaciente);

        mnuAtualizarAnamnese.setText("Anamnese");
        mnuAtualizarAnamnese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtualizarAnamneseActionPerformed(evt);
            }
        });
        mnuAtualizar.add(mnuAtualizarAnamnese);

        mnuAtualizarConsulta.setText("Consulta");
        mnuAtualizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtualizarConsultaActionPerformed(evt);
            }
        });
        mnuAtualizar.add(mnuAtualizarConsulta);

        mnuAtualizarExercicio.setText("Exercício");
        mnuAtualizarExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtualizarExercicioActionPerformed(evt);
            }
        });
        mnuAtualizar.add(mnuAtualizarExercicio);

        mnuAtualizarEquipamentos.setText("Equipamentos");
        mnuAtualizarEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtualizarEquipamentosActionPerformed(evt);
            }
        });
        mnuAtualizar.add(mnuAtualizarEquipamentos);

        mnuAtualizarFisioterapeuta.setText("Fisioterapeuta");
        mnuAtualizarFisioterapeuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtualizarFisioterapeutaActionPerformed(evt);
            }
        });
        mnuAtualizar.add(mnuAtualizarFisioterapeuta);

        mnuAtualizarProprietario.setText("Proprietário");
        mnuAtualizarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAtualizarProprietarioActionPerformed(evt);
            }
        });
        mnuAtualizar.add(mnuAtualizarProprietario);

        menuBar.add(mnuAtualizar);

        mnuBuscar.setText("Buscar");
        mnuBuscar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuBuscarMenuSelected(evt);
            }
        });

        mnuBuscarPaciente.setText("Paciente");
        mnuBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarPacienteActionPerformed(evt);
            }
        });
        mnuBuscar.add(mnuBuscarPaciente);

        mnuBuscarAnamnese.setText("Anamnese");
        mnuBuscarAnamnese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarAnamneseActionPerformed(evt);
            }
        });
        mnuBuscar.add(mnuBuscarAnamnese);

        mnuBuscarConsulta.setText("Consulta");
        mnuBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarConsultaActionPerformed(evt);
            }
        });
        mnuBuscar.add(mnuBuscarConsulta);

        mnuBuscarTodasConsultas.setText("Todas Consultas");
        mnuBuscarTodasConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarTodasConsultasActionPerformed(evt);
            }
        });
        mnuBuscar.add(mnuBuscarTodasConsultas);

        mnuBuscarFicha.setText("Ficha");
        mnuBuscarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarFichaActionPerformed(evt);
            }
        });
        mnuBuscar.add(mnuBuscarFicha);

        mnuBuscarExercicio.setText("Exercício");
        mnuBuscarExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarExercicioActionPerformed(evt);
            }
        });
        mnuBuscar.add(mnuBuscarExercicio);

        mnuBuscarEquipamentos.setText("Equipamentos");
        mnuBuscarEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarEquipamentosActionPerformed(evt);
            }
        });
        mnuBuscar.add(mnuBuscarEquipamentos);

        mnuBuscarFisioterapeuta.setText("Fisioterapeuta");
        mnuBuscarFisioterapeuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarFisioterapeutaActionPerformed(evt);
            }
        });
        mnuBuscar.add(mnuBuscarFisioterapeuta);

        mnuBuscarProprietario.setText("Proprietário");
        mnuBuscarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarProprietarioActionPerformed(evt);
            }
        });
        mnuBuscar.add(mnuBuscarProprietario);

        menuBar.add(mnuBuscar);

        mnuSair.setText("Sair");
        mnuSair.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuSairMenuSelected(evt);
            }
        });

        mnuLogout.setText("Logout");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        mnuSair.add(mnuLogout);

        mnuSairPrograma.setText("Sair");
        mnuSairPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairProgramaActionPerformed(evt);
            }
        });
        mnuSair.add(mnuSairPrograma);

        menuBar.add(mnuSair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, Short.MAX_VALUE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarConsultaActionPerformed
        consultaJF = new ConsultaJF();
        desktopPane.add(consultaJF);
        consultaJF.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarConsultaActionPerformed

    private void mnuCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarPacienteActionPerformed
        pacienteJF = new PacienteJF();
        desktopPane.add(pacienteJF);
        pacienteJF.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarPacienteActionPerformed

    private void mnuCadastrarExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarExercicioActionPerformed
        exercicioJF = new ExercicioJF();
        desktopPane.add(exercicioJF);
        exercicioJF.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarExercicioActionPerformed

    private void mnucadastrarAnamneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucadastrarAnamneseActionPerformed
        anamneseJF = new AnamneseJF();
        desktopPane.add(anamneseJF);
        anamneseJF.setVisible(true);

    }//GEN-LAST:event_mnucadastrarAnamneseActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String senha = String.valueOf(txtSenha.getPassword());
        if (!txtLogin.getText().isBlank() && !senha.isBlank()) {

            if (Proprietario.verfificarLogin(txtLogin.getText())) {
                if (Proprietario.verfificarSenha(txtLogin.getText(), senha)) {
                    menuBar.setEnabled(true);
                    menuBar.setVisible(true);
                    lblLogin.setVisible(false);
                    lblSenha.setVisible(false);
                    txtLogin.setVisible(false);
                    txtSenha.setVisible(false);
                    btnEntrar.setVisible(false);
                    lblSaida.setText("Login efetuado com sucesso");
                } else {
                    lblSaida.setText("Senha inválida");
                }
            } else if (Fisioterapeuta.verfificarLogin(txtLogin.getText())) {
                if (Fisioterapeuta.verfificarSenha(txtLogin.getText(), senha)) {
                    menuBar.setEnabled(true);
                    menuBar.setVisible(true);
                    lblLogin.setVisible(false);
                    lblSenha.setVisible(false);
                    txtLogin.setVisible(false);
                    txtSenha.setVisible(false);
                    btnEntrar.setVisible(false);

                    mnuCadastrarFisioterapeuta.setVisible(false);
                    mnuCadastrarProprietario.setVisible(false);
                    mnuCadastrarEquipamentos.setVisible(false);
                    mnuAtualizarFisioterapeuta.setVisible(false);
                    mnuAtualizarProprietario.setVisible(false);
                    mnuAtualizarEquipamentos.setVisible(false);
                    mnuBuscarFisioterapeuta.setVisible(false);
                    mnuBuscarProprietario.setVisible(false);
                    mnuBuscarEquipamentos.setVisible(false);

                    lblSaida.setText("Login efetuado com sucesso");
                } else {
                    lblSaida.setText("Senha inválida");
                }

            } else {
                lblSaida.setText("Login não encontrado");
            }
        } else {
            lblSaida.setText("Campos em branco");
        }


    }//GEN-LAST:event_btnEntrarActionPerformed

    private void mnuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarActionPerformed
        pacienteJF = new PacienteJF();
        desktopPane.add(pacienteJF);
        pacienteJF.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarActionPerformed

    private void mnuCadastrarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarProprietarioActionPerformed
        proprietarioJF = new ProprietarioJF();
        desktopPane.add(proprietarioJF);
        proprietarioJF.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarProprietarioActionPerformed

    private void mnuCadastrarFisioterapeutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarFisioterapeutaActionPerformed
        fisioterapeutaJF = new FisioterapeutaJF();
        desktopPane.add(fisioterapeutaJF);
        fisioterapeutaJF.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarFisioterapeutaActionPerformed

    private void mnuCadastrarEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarEquipamentosActionPerformed
        equipamentosJF = new EquipamentosJF();
        desktopPane.add(equipamentosJF);
        equipamentosJF.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarEquipamentosActionPerformed

    private void mnuAtualizarEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtualizarEquipamentosActionPerformed
        atualizarEquipamentoJF = new AtualizarEquipamentoJF();
        desktopPane.add(atualizarEquipamentoJF);
        atualizarEquipamentoJF.setVisible(true);
    }//GEN-LAST:event_mnuAtualizarEquipamentosActionPerformed

    private void mnuAtualizarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtualizarProprietarioActionPerformed
        atualizarProprietarioJF = new AtualizarProprietarioJF();
        desktopPane.add(atualizarProprietarioJF);
        atualizarProprietarioJF.setVisible(true);
    }//GEN-LAST:event_mnuAtualizarProprietarioActionPerformed

    private void mnuAtualizarFisioterapeutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtualizarFisioterapeutaActionPerformed
        atualizarFisioterapeutaJF = new AtualizarFisioterapeutaJF();
        desktopPane.add(atualizarFisioterapeutaJF);
        atualizarFisioterapeutaJF.setVisible(true);
    }//GEN-LAST:event_mnuAtualizarFisioterapeutaActionPerformed

    private void mnuAtualizarExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtualizarExercicioActionPerformed
        atualizarExercicioJF = new AtualizarExercicioJF();
        desktopPane.add(atualizarExercicioJF);
        atualizarExercicioJF.setVisible(true);
    }//GEN-LAST:event_mnuAtualizarExercicioActionPerformed

    private void mnuAtualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtualizarPacienteActionPerformed
        atualizarPacienteJF = new AtualizarPacienteJF();
        desktopPane.add(atualizarPacienteJF);
        atualizarPacienteJF.setVisible(true);
    }//GEN-LAST:event_mnuAtualizarPacienteActionPerformed

    private void mnuBuscarAnamneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarAnamneseActionPerformed
        buscarAnamneseJF = new BuscarAnamneseJF();
        desktopPane.add(buscarAnamneseJF);
        buscarAnamneseJF.setVisible(true);
    }//GEN-LAST:event_mnuBuscarAnamneseActionPerformed

    private void mnuAtualizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtualizarConsultaActionPerformed
        atualizarConsultaJF = new AtualizarConsultaJF();
        desktopPane.add(atualizarConsultaJF);
        atualizarConsultaJF.setVisible(true);
    }//GEN-LAST:event_mnuAtualizarConsultaActionPerformed

    private void mnuBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarPacienteActionPerformed
        buscarPacienteJF = new BuscarPacienteJF();
        desktopPane.add(buscarPacienteJF);
        buscarPacienteJF.setVisible(true);
    }//GEN-LAST:event_mnuBuscarPacienteActionPerformed

    private void mnuBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarConsultaActionPerformed
        buscarConsultaJF = new BuscarConsultaJF();
        desktopPane.add(buscarConsultaJF);
        buscarConsultaJF.setVisible(true);
    }//GEN-LAST:event_mnuBuscarConsultaActionPerformed

    private void mnuBuscarExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarExercicioActionPerformed
        buscarExercicioJF = new BuscarExercicioJF();
        desktopPane.add(buscarExercicioJF);
        buscarExercicioJF.setVisible(true);
    }//GEN-LAST:event_mnuBuscarExercicioActionPerformed

    private void mnuBuscarEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarEquipamentosActionPerformed
        buscarEquipamentoJF = new BuscarEquipamentoJF();
        desktopPane.add(buscarEquipamentoJF);
        buscarEquipamentoJF.setVisible(true);
    }//GEN-LAST:event_mnuBuscarEquipamentosActionPerformed

    private void mnuBuscarFisioterapeutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarFisioterapeutaActionPerformed
        buscarFisioterapeutaJF = new BuscarFisioterapeutaJF();
        desktopPane.add(buscarFisioterapeutaJF);
        buscarFisioterapeutaJF.setVisible(true);
    }//GEN-LAST:event_mnuBuscarFisioterapeutaActionPerformed

    private void mnuBuscarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarProprietarioActionPerformed
        buscarProprietarioJF = new BuscarProprietarioJF();
        desktopPane.add(buscarProprietarioJF);
        buscarProprietarioJF.setVisible(true);
    }//GEN-LAST:event_mnuBuscarProprietarioActionPerformed

    private void mnuCadastrarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarFichaActionPerformed
        fichaJF = new FichaJF();
        desktopPane.add(fichaJF);
        fichaJF.setVisible(true);
    }//GEN-LAST:event_mnuCadastrarFichaActionPerformed

    private void mnuBuscarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarFichaActionPerformed
        buscarFichaJF = new BuscarFichaJF();
        desktopPane.add(buscarFichaJF);
        buscarFichaJF.setVisible(true);
    }//GEN-LAST:event_mnuBuscarFichaActionPerformed

    private void mnuSairProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairProgramaActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSairProgramaActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        menuBar.setEnabled(false);
        menuBar.setVisible(false);
        lblLogin.setVisible(true);
        lblSenha.setVisible(true);
        txtLogin.setVisible(true);
        txtSenha.setVisible(true);
        btnEntrar.setVisible(true);

        mnuCadastrarFisioterapeuta.setVisible(true);
        mnuCadastrarProprietario.setVisible(true);
        mnuCadastrarEquipamentos.setVisible(true);
        mnuAtualizarFisioterapeuta.setVisible(true);
        mnuAtualizarProprietario.setVisible(true);
        mnuAtualizarEquipamentos.setVisible(true);
        mnuBuscarFisioterapeuta.setVisible(true);
        mnuBuscarProprietario.setVisible(true);
        mnuBuscarEquipamentos.setVisible(true);

        if (buscarConsultaJF.isVisible()) {
            buscarConsultaJF.setVisible(false);
        }
        if (buscarConsultasDatasJF.isVisible()) {
            buscarConsultasDatasJF.setVisible(false);
        }
        if (atualizarAnamneseJF.isVisible()) {
            atualizarAnamneseJF.setVisible(false);
        }
        if (buscarFichaJF.isVisible()) {
            buscarFichaJF.setVisible(false);
        }
        if (buscarProprietarioJF.isVisible()) {
            buscarProprietarioJF.setVisible(false);
        }
        if (buscarEquipamentoJF.isVisible()) {
            buscarEquipamentoJF.setVisible(false);
        }
        if (buscarPacienteJF.isVisible()) {
            buscarPacienteJF.setVisible(false);
        }
        if (buscarAnamneseJF.isVisible()) {
            buscarAnamneseJF.setVisible(false);
        }
        if (atualizarExercicioJF.isVisible()) {
            atualizarExercicioJF.setVisible(false);
        }
        if (atualizarProprietarioJF.isVisible()) {
            atualizarProprietarioJF.setVisible(false);
        }
        if (equipamentosJF.isVisible()) {
            equipamentosJF.setVisible(false);
        }
        if (proprietarioJF.isVisible()) {
            proprietarioJF.setVisible(false);
        }
        if (exercicioJF.isVisible()) {
            exercicioJF.setVisible(false);
        }
        if (consultaJF.isVisible()) {
            consultaJF.setVisible(false);
        }
        if (buscarFisioterapeutaJF.isVisible()) {
            buscarFisioterapeutaJF.setVisible(false);
        }

        txtLogin.setText("");
        txtSenha.setText("");
        lblSaida.setText("Logout efetuado com sucesso");
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuSairMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuSairMenuSelected
        if (lblSaida.getText().equals("Login efetuado com sucesso")) {
            lblSaida.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSairMenuSelected

    private void mnuBuscarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuBuscarMenuSelected
        if (lblSaida.getText().equals("Login efetuado com sucesso")) {
            lblSaida.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBuscarMenuSelected

    private void mnuAtualizarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuAtualizarMenuSelected
        if (lblSaida.getText().equals("Login efetuado com sucesso")) {
            lblSaida.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAtualizarMenuSelected

    private void mnuCadastrarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuCadastrarMenuSelected
        if (lblSaida.getText().equals("Login efetuado com sucesso")) {
            lblSaida.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastrarMenuSelected

    private void mnuAtualizarAnamneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAtualizarAnamneseActionPerformed
        atualizarAnamneseJF = new AtualizarAnamneseJF();
        desktopPane.add(atualizarAnamneseJF);
        atualizarAnamneseJF.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAtualizarAnamneseActionPerformed

    private void mnuBuscarTodasConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarTodasConsultasActionPerformed
        buscarConsultasDatasJF = new BuscarConsultasDatasJF();
        desktopPane.add(buscarConsultasDatasJF);
        buscarConsultasDatasJF.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuBuscarTodasConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new janelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAtualizar;
    private javax.swing.JMenuItem mnuAtualizarAnamnese;
    private javax.swing.JMenuItem mnuAtualizarConsulta;
    private javax.swing.JMenuItem mnuAtualizarEquipamentos;
    private javax.swing.JMenuItem mnuAtualizarExercicio;
    private javax.swing.JMenuItem mnuAtualizarFisioterapeuta;
    private javax.swing.JMenuItem mnuAtualizarPaciente;
    private javax.swing.JMenuItem mnuAtualizarProprietario;
    private javax.swing.JMenu mnuBuscar;
    private javax.swing.JMenuItem mnuBuscarAnamnese;
    private javax.swing.JMenuItem mnuBuscarConsulta;
    private javax.swing.JMenuItem mnuBuscarEquipamentos;
    private javax.swing.JMenuItem mnuBuscarExercicio;
    private javax.swing.JMenuItem mnuBuscarFicha;
    private javax.swing.JMenuItem mnuBuscarFisioterapeuta;
    private javax.swing.JMenuItem mnuBuscarPaciente;
    private javax.swing.JMenuItem mnuBuscarProprietario;
    private javax.swing.JMenuItem mnuBuscarTodasConsultas;
    private javax.swing.JMenu mnuCadastrar;
    private javax.swing.JMenuItem mnuCadastrarConsulta;
    private javax.swing.JMenuItem mnuCadastrarEquipamentos;
    private javax.swing.JMenuItem mnuCadastrarExercicio;
    private javax.swing.JMenuItem mnuCadastrarFicha;
    private javax.swing.JMenuItem mnuCadastrarFisioterapeuta;
    private javax.swing.JMenuItem mnuCadastrarPaciente;
    private javax.swing.JMenuItem mnuCadastrarProprietario;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JMenuItem mnuSairPrograma;
    private javax.swing.JMenuItem mnucadastrarAnamnese;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
