package br.com.fisioterapia.jframe.atualizar;

import br.com.fisioterapia.database.consulta.Exercicio;
import java.beans.PropertyVetoException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class AtualizarExercicioJF extends javax.swing.JInternalFrame {

    public static int codExercicio;

    /**
     * Creates new form AtualizarAnamneseFJ
     */
    public AtualizarExercicioJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomePesquisa = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JButton();
        lblNomePesquisa = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSaida = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Atualizar Exercício");
        setPreferredSize(new java.awt.Dimension(500, 500));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                zerarVariaveis(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(txtNomePesquisa);
        txtNomePesquisa.setBounds(110, 20, 241, 30);

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");
        getContentPane().add(lblDescricao);
        lblDescricao.setBounds(30, 160, 70, 30);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(180, 280, 90, 35);

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 160, 260, 100);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(180, 60, 90, 23);

        lblNomePesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomePesquisa.setText("Nome:");
        getContentPane().add(lblNomePesquisa);
        lblNomePesquisa.setBounds(50, 20, 48, 25);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(50, 110, 48, 25);
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 110, 241, 30);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(40, 360, 330, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zerarVariaveis(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_zerarVariaveis
        AtualizarExercicioJF.codExercicio = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_zerarVariaveis

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (!txtNomePesquisa.getText().isBlank()) {

            Exercicio e1 = new Exercicio(txtNomePesquisa.getText());
            if (e1.verificarNomeExercicio()) {
                e1 = Exercicio.buscarExercicio(txtNomePesquisa.getText());
                txtNome.setText(e1.getNome());
                txtDescricao.setText(e1.getDescricao());

                AtualizarExercicioJF.codExercicio = e1.getCodExercicio();
                lblSaida.setText("Exercicio encontrado");
            } else {
                lblSaida.setText("Exercicio não encontrado");
            }
        } else {
            lblSaida.setText("Campo em branco");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String nome = txtNome.getText();
        String descricao = txtDescricao.getText();

        if (!nome.isBlank() && !descricao.isBlank()) {
            Exercicio e1;
            if (AtualizarExercicioJF.codExercicio > 0) {
                e1 = new Exercicio(nome, descricao, AtualizarExercicioJF.codExercicio);
                e1.updateExercicio();
                AtualizarExercicioJF.codExercicio = 0;
                lblSaida.setText("Dados atualizados com sucesso!!!");
            } else {
                lblSaida.setText("Busque um exercicio pelo nome antes de atualizar");
            }

        } else {
            lblSaida.setText("Campos em branco!!!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomePesquisa;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomePesquisa;
    // End of variables declaration//GEN-END:variables
}
