package br.com.fisioterapia.jframe.atualizar;

import br.com.fisioterapia.database.pessoas.Fisioterapeuta;
import java.beans.PropertyVetoException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class AtualizarFisioterapeutaJF extends javax.swing.JInternalFrame {

    public static int codPessoa = 0;

    /**
     * Creates new form AtualizarFisioterapeutaJF
     */
    public AtualizarFisioterapeutaJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCpf = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        lblEndereco = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCrefito = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblBuscarCpf = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtCpfFisioterapeutaBusca = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCrefito = new javax.swing.JFormattedTextField();
        lblSaida = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Atualizar Fisioterapeuta");
        setMinimumSize(new java.awt.Dimension(400, 520));
        setPreferredSize(new java.awt.Dimension(411, 549));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                zerarVariaveis(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        lblCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpf.setText("CPF");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(60, 120, 49, 24);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(130, 440, 81, 23);

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(40, 200, 67, 24);

        lblRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRg.setText("RG");
        getContentPane().add(lblRg);
        lblRg.setBounds(60, 160, 49, 24);

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(40, 240, 67, 24);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("E-mail");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(50, 280, 67, 24);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 80, 248, 29);

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(110, 200, 360, 29);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(50, 80, 49, 24);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(100, 280, 248, 29);

        lblCrefito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCrefito.setText("CREFITO");
        getContentPane().add(lblCrefito);
        lblCrefito.setBounds(30, 320, 67, 24);

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin);
        txtLogin.setBounds(100, 360, 248, 29);

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(50, 400, 38, 17);

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLogin.setText("Login");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(60, 370, 50, 17);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(100, 400, 244, 30);

        lblBuscarCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscarCpf.setText("CPF");
        getContentPane().add(lblBuscarCpf);
        lblBuscarCpf.setBounds(40, 10, 49, 24);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(160, 50, 90, 23);

        try {
            txtCpfFisioterapeutaBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfFisioterapeutaBusca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpfFisioterapeutaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfFisioterapeutaBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfFisioterapeutaBusca);
        txtCpfFisioterapeutaBusca.setBounds(90, 10, 120, 30);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(110, 120, 120, 30);

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AA.AAA.AAA-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtRg);
        txtRg.setBounds(110, 160, 120, 30);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(100, 240, 110, 30);

        try {
            txtCrefito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-**")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCrefito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCrefito);
        txtCrefito.setBounds(100, 320, 100, 30);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(30, 470, 330, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCpfFisioterapeutaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfFisioterapeutaBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfFisioterapeutaBuscaActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void zerarVariaveis(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_zerarVariaveis
        AtualizarFisioterapeutaJF.codPessoa = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_zerarVariaveis

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cpfB1[] = txtCpfFisioterapeutaBusca.getText().split("-");
        String cpfB2[] = cpfB1[0].split("\\.");
        String testeCpfB = cpfB2[0] + cpfB2[1] + cpfB2[2] + cpfB1[1];
        long cpfB;

        if (!testeCpfB.isBlank()) {
            cpfB = Long.parseLong(testeCpfB);
            Fisioterapeuta f1 = new Fisioterapeuta(cpfB);
            if (f1.verificarFisioterapeuta()) { //Para saber se é um fisioterapeuta,paciente ou Proprietario.  
                f1 = Fisioterapeuta.buscarFisioterapeuta(cpfB);
                txtNome.setText(f1.getNome());
                txtCpf.setText(String.valueOf(f1.getCpf()));
                txtRg.setText(f1.getRg());
                txtEndereco.setText(f1.getEndereco());
                txtTelefone.setText(String.valueOf(f1.getTelefone()));
                txtEmail.setText(f1.getEmail());
                txtCrefito.setText(f1.getCrefito());
                txtLogin.setText(f1.getUsuario());
                txtSenha.setText(f1.getSenha());

                AtualizarFisioterapeutaJF.codPessoa = f1.getCodPessoa();
                lblSaida.setText("Fisioterapeuta encontrado");

            } else {
                lblSaida.setText("Fisioterapeuta não encontrado!!!");
            }

        } else {
            lblSaida.setText("Campo em branco");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String endereco = txtEndereco.getText();
        String usuario = txtLogin.getText();
        String senha = new String(txtSenha.getPassword());

        String rg1[] = txtRg.getText().split("-");
        String rg2[] = rg1[0].split("\\.");
        String rg = rg2[0] + rg2[1] + rg2[2] + rg1[1];

        String cpf1[] = txtCpf.getText().split("-");
        String cpf2[] = cpf1[0].split("\\.");
        String testeCpf = cpf2[0] + cpf2[1] + cpf2[2] + cpf1[1];
        long cpf;

        String telefone1[] = txtTelefone.getText().split("-");
        long telefone;

        String crefito1[] = txtCrefito.getText().split("-");
        String crefito = crefito1[0] + crefito1[1];

        if (!nome.isBlank() && !email.isBlank() && !endereco.isBlank() && !rg.isBlank() && !testeCpf.isBlank() && !telefone1[0].isBlank() && !telefone1[1].isBlank() && !usuario.isBlank() && !senha.isBlank() && !crefito.isBlank()) {

            cpf = Long.parseLong(testeCpf);

            String telefone2[] = telefone1[0].split(" ");
            String testeTelefone = telefone2[0] + telefone2[1] + telefone1[1];

            telefone = Long.parseLong(testeTelefone);

            Fisioterapeuta f1;
            if (AtualizarFisioterapeutaJF.codPessoa > 0) {
                f1 = new Fisioterapeuta(crefito, usuario, senha, codPessoa, nome, cpf, rg, telefone, email, endereco);
                f1.updateFisioterapeuta();
                AtualizarFisioterapeutaJF.codPessoa = 0;
                lblSaida.setText("Dados atualizados com sucesso!!!");
            } else {
                lblSaida.setText("Busque um fisioterapeuta pelo CPF antes de atualizar");
            }

        } else {
            lblSaida.setText("Campos em branco!!!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblBuscarCpf;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCrefito;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtCpfFisioterapeutaBusca;
    private javax.swing.JFormattedTextField txtCrefito;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
