package br.com.fisioterapia.jframe.atualizar;

import br.com.fisioterapia.database.pessoas.Proprietario;
import java.beans.PropertyVetoException;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class AtualizarProprietarioJF extends javax.swing.JInternalFrame {

    public static int codPessoa;

    /**
     * Creates new form AtualizarProprietarioJF
     */
    public AtualizarProprietarioJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblRg = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JLabel();
        lblBuscaCpf = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblSaida = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtCnpj = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtBuscaCpf = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Atualizar Proprietário");
        setPreferredSize(new java.awt.Dimension(409, 533));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                zerarVariaveis(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("E-mail");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(20, 330, 67, 20);

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(80, 230, 360, 30);

        lblCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCnpj.setText("CNPJ");
        getContentPane().add(lblCnpj);
        lblCnpj.setBounds(20, 150, 60, 20);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(20, 70, 49, 20);

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(10, 240, 67, 20);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(80, 320, 248, 30);

        lblRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRg.setText("RG");
        getContentPane().add(lblRg);
        lblRg.setBounds(30, 190, 49, 20);

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(10, 290, 67, 20);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(140, 440, 75, 20);

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(20, 410, 67, 20);

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin);
        txtLogin.setBounds(80, 360, 248, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(80, 400, 248, 30);

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLogin.setText("Login");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(20, 370, 67, 20);

        lblBuscaCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscaCpf.setText("CPF");
        getContentPane().add(lblBuscaCpf);
        lblBuscaCpf.setBounds(30, 20, 60, 20);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(230, 10, 80, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(70, 60, 248, 30);

        lblCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpf.setText("CPF ");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(20, 110, 40, 20);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(30, 470, 330, 20);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(70, 100, 120, 30);

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCnpj);
        txtCnpj.setBounds(70, 140, 150, 30);

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AA.AAA.AAA-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtRg);
        txtRg.setBounds(70, 180, 120, 30);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(80, 280, 110, 30);

        try {
            txtBuscaCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscaCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscaCpf);
        txtBuscaCpf.setBounds(70, 10, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String endereco = txtEndereco.getText();
        String usuario = txtLogin.getText();
        String senha = new String(txtSenha.getPassword());

        String rg1[] = txtRg.getText().split("-");
        String rg2[] = rg1[0].split("\\.");
        String rg = rg2[0] + rg2[1] + rg2[2] + rg1[1];

        String cpf1[] = txtCpf.getText().split("-");
        String cpf2[] = cpf1[0].split("\\.");
        String testeCpf = cpf2[0] + cpf2[1] + cpf2[2] + cpf1[1];
        long cpf;

        String telefone1[] = txtTelefone.getText().split("-");
        long telefone;

        String cnpj1[] = txtCnpj.getText().split("/");
        String cnpj2[] = cnpj1[0].split("\\.");
        String cnpj3[] = cnpj1[1].split("-");
        String testeCnpj = cnpj2[0] + cnpj2[1] + cnpj2[2] + cnpj3[0] + cnpj3[1];
        long cnpj;

        if (!nome.isBlank() && !email.isBlank() && !endereco.isBlank() && !rg.isBlank() && !testeCpf.isBlank() && !telefone1[0].isBlank() && !telefone1[1].isBlank() && !usuario.isBlank() && !senha.isBlank() && !testeCnpj.isBlank()) {

            cpf = Long.parseLong(testeCpf);

            cnpj = Long.parseLong(testeCnpj);

            String telefone2[] = telefone1[0].split(" ");
            String testeTelefone = telefone2[0] + telefone2[1] + telefone1[1];

            telefone = Long.parseLong(testeTelefone);

            Proprietario p1;
            if (AtualizarProprietarioJF.codPessoa > 0) {
                p1 = new Proprietario(cnpj, usuario, senha, AtualizarProprietarioJF.codPessoa, nome, cpf, rg, telefone, email, endereco);
                p1.updateProprietario();
                AtualizarProprietarioJF.codPessoa = 0;
                lblSaida.setText("Dados atualizados com sucesso!!!");
            } else {
                lblSaida.setText("Busque um Proprietario pelo CPF antes de atualizar");
            }
        } else {
            lblSaida.setText("Campos em branco!!!");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtBuscaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaCpfActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cpfB1[] = txtBuscaCpf.getText().split("-");
        String cpfB2[] = cpfB1[0].split("\\.");
        String testeCpfB = cpfB2[0] + cpfB2[1] + cpfB2[2] + cpfB1[1];
        long cpfB;

        if (!testeCpfB.isBlank()) {
            cpfB = Long.parseLong(testeCpfB);
            Proprietario p1 = new Proprietario(cpfB);
            if (p1.verificarProprietario()) { //Para saber se é um fisioterapeuta,paciente ou Proprietario.  
                p1 = Proprietario.buscarProprietario(cpfB);
                txtNome.setText(p1.getNome());
                txtCpf.setText(String.valueOf(p1.getCpf()));
                txtRg.setText(p1.getRg());
                txtEndereco.setText(p1.getEndereco());
                txtTelefone.setText(String.valueOf(p1.getTelefone()));
                txtEmail.setText(p1.getEmail());
                txtCnpj.setText(String.valueOf(p1.getCnpj()));
                txtLogin.setText(p1.getLogin());
                txtSenha.setText(p1.getSenha());

                AtualizarProprietarioJF.codPessoa = p1.getCodPessoa();
                lblSaida.setText("Proprietario encontrado");
            } else {
                lblSaida.setText("Proprietario não encontrado!!!");
            }

        } else {
            lblSaida.setText("Campo em branco");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void zerarVariaveis(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_zerarVariaveis
        AtualizarProprietarioJF.codPessoa = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_zerarVariaveis


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblBuscaCpf;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JFormattedTextField txtBuscaCpf;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
