package br.com.fisioterapia.jframe.atualizar;

import br.com.fisioterapia.database.pessoas.Paciente;
import java.beans.PropertyVetoException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class AtualizarPacienteJF extends javax.swing.JInternalFrame {

    public static int codPaciente = 0;

    /**
     * Creates new form AtualiarPaciente
     */
    public AtualizarPacienteJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtualizar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblCpfBusca = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtCpfPacienteBusca = new javax.swing.JFormattedTextField();
        txtCpfPaciente = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        lblSaida = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Atualizar Paciente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(131, 33));
        setNormalBounds(new java.awt.Rectangle(0, 0, 121, 0));
        setPreferredSize(new java.awt.Dimension(500, 500));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                zerarVariaveis(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(180, 330, 75, 23);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 90, 49, 24);

        lblCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpf.setText("CPF");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(30, 130, 49, 24);

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(10, 210, 67, 24);

        lblRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRg.setText("RG");
        getContentPane().add(lblRg);
        lblRg.setBounds(30, 170, 49, 24);

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(10, 250, 67, 24);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("E-mail");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(20, 290, 67, 24);
        getContentPane().add(txtNome);
        txtNome.setBounds(90, 90, 248, 29);

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(90, 210, 360, 29);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(90, 290, 248, 29);

        lblCpfBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpfBusca.setText("CPF");
        getContentPane().add(lblCpfBusca);
        lblCpfBusca.setBounds(30, 10, 49, 24);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(170, 50, 80, 23);
        btnBuscar.getAccessibleContext().setAccessibleName("");
        btnBuscar.getAccessibleContext().setAccessibleDescription("");

        try {
            txtCpfPacienteBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfPacienteBusca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpfPacienteBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfPacienteBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfPacienteBusca);
        txtCpfPacienteBusca.setBounds(90, 10, 120, 30);

        try {
            txtCpfPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfPaciente);
        txtCpfPaciente.setBounds(90, 130, 120, 30);

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AA.AAA.AAA-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtRg);
        txtRg.setBounds(90, 170, 120, 30);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(90, 250, 110, 30);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(30, 370, 330, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String endereco = txtEndereco.getText();

        String rg1[] = txtRg.getText().split("-");
        String rg2[] = rg1[0].split("\\.");
        String rg = rg2[0] + rg2[1] + rg2[2] + rg1[1];

        String cpf1[] = txtCpfPaciente.getText().split("-");
        String cpf2[] = cpf1[0].split("\\.");
        String testeCpf = cpf2[0] + cpf2[1] + cpf2[2] + cpf1[1];
        long cpf;

        String telefone1[] = txtTelefone.getText().split("-");
        long telefone;

        if (!nome.isBlank() && !email.isBlank() && !endereco.isBlank() && !rg.isBlank() && !testeCpf.isBlank() && !telefone1[0].isBlank() && !telefone1[1].isBlank()) {
            cpf = Long.parseLong(testeCpf);

            String telefone2[] = telefone1[0].split(" ");
            String testeTelefone = telefone2[0] + telefone2[1] + telefone1[1];

            telefone = Long.parseLong(testeTelefone);

            Paciente p1;
            if (AtualizarPacienteJF.codPaciente > 0) {
                p1 = new Paciente(AtualizarPacienteJF.codPaciente, nome, cpf, rg, telefone, email, endereco);
                p1.UpdatePaciente();
                AtualizarPacienteJF.codPaciente = 0;
                lblSaida.setText("Dados atualizados com sucesso!!!");
            } else {
                lblSaida.setText("Busque um paciente pelo CPF antes de atualizar");
            }

        } else {
            lblSaida.setText("Campos em branco!!!");
        }


    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCpfPacienteBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfPacienteBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfPacienteBuscaActionPerformed

    private void txtCpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfPacienteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String cpfB1[] = txtCpfPacienteBusca.getText().split("-");
        String cpfB2[] = cpfB1[0].split("\\.");
        String testeCpfB = cpfB2[0] + cpfB2[1] + cpfB2[2] + cpfB1[1];
        long cpfB;

        if (!testeCpfB.isBlank()) {
            cpfB = Long.parseLong(testeCpfB);
            Paciente p1 = new Paciente(cpfB);
            if (p1.verificarCpf()) {
                p1 = Paciente.BuscarPaciente(cpfB);
                txtNome.setText(p1.getNome());
                txtCpfPaciente.setText(String.valueOf(p1.getCpf()));
                txtRg.setText(p1.getRg());
                txtEndereco.setText(p1.getEndereco());
                txtTelefone.setText(String.valueOf(p1.getTelefone()));
                txtEmail.setText(p1.getEmail());
                AtualizarPacienteJF.codPaciente = p1.getCodPessoa();
                lblSaida.setText("Paciente encontrado");
            } else {
                lblSaida.setText("Cpf não encontrado");
            }
        } else {
            lblSaida.setText("Campo em branco");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void zerarVariaveis(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_zerarVariaveis
        AtualizarPacienteJF.codPaciente = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_zerarVariaveis


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpfBusca;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JFormattedTextField txtCpfPaciente;
    private javax.swing.JFormattedTextField txtCpfPacienteBusca;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
