package br.com.fisioterapia.jframe.buscar;

import br.com.fisioterapia.database.pessoas.Fisioterapeuta;
import java.beans.PropertyVetoException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class BuscarFisioterapeutaJF extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarFisioterapeutaJF
     */
    public BuscarFisioterapeutaJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcurar = new javax.swing.JButton();
        lblTituloNome = new javax.swing.JLabel();
        lblTituloCpf = new javax.swing.JLabel();
        lblTituloRg = new javax.swing.JLabel();
        lblTituloEndereco = new javax.swing.JLabel();
        lblTituloTelefone = new javax.swing.JLabel();
        lblTituloEmail = new javax.swing.JLabel();
        lblBuscarCpf = new javax.swing.JLabel();
        txtCpfFisioterapeutaBusca = new javax.swing.JFormattedTextField();
        lblTituloCrefito = new javax.swing.JLabel();
        lblSaida = new javax.swing.JLabel();
        lblTituloLogin = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCrefito = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Fisioterapeuta");
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcurar);
        btnProcurar.setBounds(130, 70, 100, 30);

        lblTituloNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloNome.setText("Nome:");
        getContentPane().add(lblTituloNome);
        lblTituloNome.setBounds(10, 120, 60, 30);

        lblTituloCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloCpf.setText("CPF:");
        getContentPane().add(lblTituloCpf);
        lblTituloCpf.setBounds(10, 160, 40, 20);

        lblTituloRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloRg.setText("RG:");
        getContentPane().add(lblTituloRg);
        lblTituloRg.setBounds(10, 200, 30, 20);

        lblTituloEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloEndereco.setText("Endereço:");
        getContentPane().add(lblTituloEndereco);
        lblTituloEndereco.setBounds(10, 240, 63, 20);

        lblTituloTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloTelefone.setText("Telefone:");
        getContentPane().add(lblTituloTelefone);
        lblTituloTelefone.setBounds(10, 280, 60, 20);

        lblTituloEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloEmail.setText("E-mail:");
        getContentPane().add(lblTituloEmail);
        lblTituloEmail.setBounds(10, 320, 50, 20);

        lblBuscarCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscarCpf.setText("CPF");
        getContentPane().add(lblBuscarCpf);
        lblBuscarCpf.setBounds(70, 20, 49, 24);

        try {
            txtCpfFisioterapeutaBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfFisioterapeutaBusca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpfFisioterapeutaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfFisioterapeutaBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfFisioterapeutaBusca);
        txtCpfFisioterapeutaBusca.setBounds(120, 20, 120, 30);

        lblTituloCrefito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloCrefito.setText("Crefito:");
        getContentPane().add(lblTituloCrefito);
        lblTituloCrefito.setBounds(10, 360, 60, 20);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(30, 440, 330, 20);

        lblTituloLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloLogin.setText("Login:");
        getContentPane().add(lblTituloLogin);
        lblTituloLogin.setBounds(10, 400, 50, 17);

        txtNome.setEditable(false);
        getContentPane().add(txtNome);
        txtNome.setBounds(90, 120, 248, 29);

        txtEndereco.setEditable(false);
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(90, 240, 360, 29);

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(90, 320, 248, 29);

        txtUsuario.setEditable(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(90, 400, 248, 29);

        txtCpf.setEditable(false);
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(90, 160, 120, 30);

        txtRg.setEditable(false);
        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AA.AAA.AAA-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtRg);
        txtRg.setBounds(90, 200, 120, 30);

        txtTelefone.setEditable(false);
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(90, 280, 110, 30);

        txtCrefito.setEditable(false);
        try {
            txtCrefito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-**")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCrefito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCrefito);
        txtCrefito.setBounds(90, 360, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfFisioterapeutaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfFisioterapeutaBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfFisioterapeutaBuscaActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        String cpfB1[] = txtCpfFisioterapeutaBusca.getText().split("-");
        String cpfB2[] = cpfB1[0].split("\\.");
        String testeCpfB = cpfB2[0] + cpfB2[1] + cpfB2[2] + cpfB1[1];
        long cpfB;

        if (!testeCpfB.isBlank()) {
            cpfB = Long.parseLong(testeCpfB);
            Fisioterapeuta f1 = new Fisioterapeuta(cpfB);
            if (f1.verificarFisioterapeuta()) { //Para saber se é um fisioterapeuta,paciente ou Proprietario.  
                f1 = Fisioterapeuta.buscarFisioterapeuta(cpfB);
                txtNome.setText(f1.getNome());
                txtCpf.setText(String.valueOf(f1.getCpf()));
                txtRg.setText(f1.getRg());
                txtEndereco.setText(f1.getEndereco());
                txtTelefone.setText(String.valueOf(f1.getTelefone()));
                txtEmail.setText(f1.getEmail());
                txtCrefito.setText(f1.getCrefito());
                txtUsuario.setText(f1.getUsuario());

                lblSaida.setText("Fisioterapeuta encontrado");

            } else {
                lblSaida.setText("Fisioterapeuta não encontrado!!!");
            }

        } else {
            lblSaida.setText("Campo em branco");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcurar;
    private javax.swing.JLabel lblBuscarCpf;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblTituloCpf;
    private javax.swing.JLabel lblTituloCrefito;
    private javax.swing.JLabel lblTituloEmail;
    private javax.swing.JLabel lblTituloEndereco;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JLabel lblTituloNome;
    private javax.swing.JLabel lblTituloRg;
    private javax.swing.JLabel lblTituloTelefone;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtCpfFisioterapeutaBusca;
    private javax.swing.JFormattedTextField txtCrefito;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
