package br.com.fisioterapia.jframe.buscar;

import br.com.fisioterapia.database.consulta.Exercicio;
import java.beans.PropertyVetoException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class BuscarExercicioJF extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarExercicioJF
     */
    public BuscarExercicioJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        btnBusca = new javax.swing.JButton();
        txtBuscarNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblSaida = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Exercicio");
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(23, 23, 48, 25);

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");
        getContentPane().add(lblDescricao);
        lblDescricao.setBounds(10, 120, 70, 30);

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBusca);
        btnBusca.setBounds(120, 60, 71, 35);
        getContentPane().add(txtBuscarNome);
        txtBuscarNome.setBounds(70, 20, 200, 30);

        txtDescricao.setEditable(false);
        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 130, 270, 170);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(20, 310, 330, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        if (!txtBuscarNome.getText().isBlank()) {
            Exercicio e1 = new Exercicio(txtBuscarNome.getText());
            if (e1.verificarNomeExercicio()) {
                e1 = Exercicio.buscarExercicio(txtBuscarNome.getText());
                txtDescricao.setText(e1.getDescricao());
                lblSaida.setText("Exercicio encontrado");
            } else {
                lblSaida.setText("Exercicio não encontrado");
            }
        } else {
            lblSaida.setText("Campo em branco");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JTextField txtBuscarNome;
    private javax.swing.JTextArea txtDescricao;
    // End of variables declaration//GEN-END:variables
}
