package br.com.fisioterapia.jframe.buscar;

import br.com.fisioterapia.database.pessoas.Proprietario;
import java.beans.PropertyVetoException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class BuscarProprietarioJF extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarProprietarioJF
     */
    public BuscarProprietarioJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcurar = new javax.swing.JButton();
        lblTituloNome = new javax.swing.JLabel();
        lblTituloCpf = new javax.swing.JLabel();
        lblTituloRg = new javax.swing.JLabel();
        lblTituloEndereco = new javax.swing.JLabel();
        lblTituloTelefone = new javax.swing.JLabel();
        lblTituloEmail = new javax.swing.JLabel();
        lblSaida = new javax.swing.JLabel();
        lblTituloLogin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblBuscaCpf = new javax.swing.JLabel();
        txtBuscaCpf = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtCnpj = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Proprietário");
        setPreferredSize(new java.awt.Dimension(500, 800));
        getContentPane().setLayout(null);

        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcurar);
        btnProcurar.setBounds(260, 10, 100, 30);

        lblTituloNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloNome.setText("Nome:");
        getContentPane().add(lblTituloNome);
        lblTituloNome.setBounds(20, 90, 60, 30);

        lblTituloCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloCpf.setText("CPF:");
        getContentPane().add(lblTituloCpf);
        lblTituloCpf.setBounds(20, 140, 40, 20);

        lblTituloRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloRg.setText("RG:");
        getContentPane().add(lblTituloRg);
        lblTituloRg.setBounds(20, 210, 30, 20);

        lblTituloEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloEndereco.setText("Endereço:");
        getContentPane().add(lblTituloEndereco);
        lblTituloEndereco.setBounds(20, 250, 63, 20);

        lblTituloTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloTelefone.setText("Telefone:");
        getContentPane().add(lblTituloTelefone);
        lblTituloTelefone.setBounds(20, 290, 60, 20);

        lblTituloEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloEmail.setText("E-mail:");
        getContentPane().add(lblTituloEmail);
        lblTituloEmail.setBounds(20, 330, 50, 20);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(50, 430, 330, 20);

        lblTituloLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloLogin.setText("Login:");
        getContentPane().add(lblTituloLogin);
        lblTituloLogin.setBounds(20, 370, 50, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("CNPJ:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 180, 60, 20);

        lblBuscaCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscaCpf.setText("CPF:");
        getContentPane().add(lblBuscaCpf);
        lblBuscaCpf.setBounds(20, 20, 60, 20);

        try {
            txtBuscaCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscaCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscaCpf);
        txtBuscaCpf.setBounds(70, 20, 120, 30);

        txtNome.setEditable(false);
        getContentPane().add(txtNome);
        txtNome.setBounds(100, 90, 248, 29);

        txtEndereco.setEditable(false);
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(100, 250, 360, 30);

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(100, 330, 248, 30);

        txtLogin.setEditable(false);
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin);
        txtLogin.setBounds(100, 370, 248, 30);

        txtCpf.setEditable(false);
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(100, 130, 120, 30);

        txtCnpj.setEditable(false);
        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCnpj);
        txtCnpj.setBounds(100, 170, 150, 30);

        txtTelefone.setEditable(false);
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(100, 290, 110, 30);

        txtRg.setEditable(false);
        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AA.AAA.AAA-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtRg);
        txtRg.setBounds(100, 210, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        String cnpjB1[] = txtBuscaCpf.getText().split("-");
        String cnpjB2[] = cnpjB1[0].split("\\.");
        String testeCpfB = cnpjB2[0] + cnpjB2[1] + cnpjB2[2] + cnpjB1[1];
        long cpfB;

        if (!testeCpfB.isBlank()) {
            cpfB = Long.parseLong(testeCpfB);
            Proprietario p1 = new Proprietario(cpfB);
            if (p1.verificarProprietario()) { //Para saber se é um fisioterapeuta,paciente ou Proprietario.
                p1 = Proprietario.buscarProprietario(cpfB);
                txtNome.setText(p1.getNome());
                txtCnpj.setText(String.valueOf(p1.getCnpj()));
                txtRg.setText(p1.getRg());
                txtEndereco.setText(p1.getEndereco());
                txtTelefone.setText(String.valueOf(p1.getTelefone()));
                txtEmail.setText(p1.getEmail());
                txtLogin.setText(p1.getLogin());
                txtCpf.setText(String.valueOf(p1.getCpf()));
                lblSaida.setText("Proprietario encontrado");

            } else {
                lblSaida.setText("Proprietario não encontrado!!!");
            }

        } else {
            lblSaida.setText("Campo em branco");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void txtBuscaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaCpfActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcurar;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBuscaCpf;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblTituloCpf;
    private javax.swing.JLabel lblTituloEmail;
    private javax.swing.JLabel lblTituloEndereco;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JLabel lblTituloNome;
    private javax.swing.JLabel lblTituloRg;
    private javax.swing.JLabel lblTituloTelefone;
    private javax.swing.JFormattedTextField txtBuscaCpf;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
