package br.com.fisioterapia.jframe.buscar;

import br.com.fisioterapia.database.consulta.Exercicio;
import br.com.fisioterapia.database.consulta.Equipamentos;
import java.beans.PropertyVetoException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class BuscarEquipamentoJF extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarEquipamentoJF
     */
    public BuscarEquipamentoJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloNome = new javax.swing.JLabel();
        lblTituloQuantidade = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscarNome = new javax.swing.JTextField();
        lblTituloDescricao = new javax.swing.JLabel();
        lblTituloExercicio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblSaida = new javax.swing.JLabel();
        txtExercicio = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Equipamento");
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        lblTituloNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloNome.setText("Nome:");
        getContentPane().add(lblTituloNome);
        lblTituloNome.setBounds(20, 20, 48, 25);

        lblTituloQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloQuantidade.setText("Quantidade:");
        getContentPane().add(lblTituloQuantidade);
        lblTituloQuantidade.setBounds(10, 240, 80, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(120, 60, 100, 35);
        getContentPane().add(txtBuscarNome);
        txtBuscarNome.setBounds(70, 20, 200, 30);

        lblTituloDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloDescricao.setText("Descrição:");
        getContentPane().add(lblTituloDescricao);
        lblTituloDescricao.setBounds(10, 120, 70, 30);

        lblTituloExercicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloExercicio.setText("Exercicio:");
        getContentPane().add(lblTituloExercicio);
        lblTituloExercicio.setBounds(10, 280, 80, 30);

        txtDescricao.setEditable(false);
        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 120, 330, 100);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(10, 320, 430, 20);

        txtExercicio.setEditable(false);
        getContentPane().add(txtExercicio);
        txtExercicio.setBounds(110, 280, 250, 30);

        txtQuantidade.setEditable(false);
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(110, 240, 50, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String buscarNome = txtBuscarNome.getText();

        if (!buscarNome.isBlank()) {
            Equipamentos e1 = new Equipamentos(buscarNome);
            if (e1.verificarNomeEquipamento()) {
                e1 = Equipamentos.buscarEquipamento(buscarNome);
                txtDescricao.setText(e1.getDescricao());
                txtQuantidade.setText(String.valueOf(e1.getQuantidade()));
                Exercicio e2 = Exercicio.buscarExercicioId(e1.getCodExercicio());
                txtExercicio.setText(e2.getNome());
                lblSaida.setText("Equipamento encontrado");
            } else {
                lblSaida.setText("Equipamento não encontrado!!!");
            }
        } else {
            lblSaida.setText("Campo de busca em branco");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblTituloDescricao;
    private javax.swing.JLabel lblTituloExercicio;
    private javax.swing.JLabel lblTituloNome;
    private javax.swing.JLabel lblTituloQuantidade;
    private javax.swing.JTextField txtBuscarNome;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtExercicio;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
