package br.com.fisioterapia.jframe.buscar;

import br.com.fisioterapia.database.consulta.Consulta;
import java.beans.PropertyVetoException;
import java.text.ParseException;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class BuscarConsultasDatasJF extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarConsultaJF
     */
    public BuscarConsultasDatasJF() {           
        initComponents();
        try{
          this.setMaximum(true);  
        } catch(PropertyVetoException p){
           lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarDataInicial = new javax.swing.JLabel();
        txtBuscarDataInicial = new javax.swing.JFormattedTextField();
        lblSaida = new javax.swing.JLabel();
        lblBuscarDataFinal = new javax.swing.JLabel();
        txtBuscarDataFinal = new javax.swing.JFormattedTextField();
        jScrollPaneTabela = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Consultas por intervalo de datas");
        setPreferredSize(new java.awt.Dimension(784, 576));
        getContentPane().setLayout(null);

        lblBuscarDataInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscarDataInicial.setText("Data Inicial:");
        getContentPane().add(lblBuscarDataInicial);
        lblBuscarDataInicial.setBounds(40, 10, 80, 30);

        try {
            txtBuscarDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscarDataInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscarDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDataInicialActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscarDataInicial);
        txtBuscarDataInicial.setBounds(130, 10, 90, 30);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(30, 460, 610, 20);

        lblBuscarDataFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscarDataFinal.setText("Data Final:");
        getContentPane().add(lblBuscarDataFinal);
        lblBuscarDataFinal.setBounds(250, 10, 80, 30);

        try {
            txtBuscarDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscarDataFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscarDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDataFinalActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscarDataFinal);
        txtBuscarDataFinal.setBounds(330, 10, 90, 30);

        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Horário", "Paciente", "CPF", "Fisioterapeuta", "CPF"
            }
        ));
        tblConsultas.setCellSelectionEnabled(true);
        jScrollPaneTabela.setViewportView(tblConsultas);

        getContentPane().add(jScrollPaneTabela);
        jScrollPaneTabela.setBounds(40, 60, 1000, 350);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(520, 430, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDataInicialActionPerformed

    private void txtBuscarDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDataFinalActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        tblConsultas.setDefaultEditor(Object.class, null);//Torna a tabela não editável
        DefaultTableModel tblConsultas1 = (DefaultTableModel) tblConsultas.getModel();//Cria um modelo para editar a tabela
        tblConsultas1.setRowCount(0);//Zera a tabela para outra pesquisa
        LocalDate dataInicial;
        LocalDate dataFinal;
        Duration duracao;
        long diferencaData;

        LocalTime horarioConsulta;
        try {
            dataInicial = LocalDate.parse(txtBuscarDataInicial.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
            dataFinal = LocalDate.parse(txtBuscarDataFinal.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
            duracao = Duration.between(dataInicial.atStartOfDay(), dataFinal.atStartOfDay());
            diferencaData = duracao.toDays();
            if (diferencaData > 0) {
                int qtdConsulta = 0;
                qtdConsulta = Consulta.countConsulta(dataInicial, dataFinal);
                if (qtdConsulta > 0) {
                    String[][] consultas = Consulta.obterConsultas(qtdConsulta, dataInicial, dataFinal);
                    for (int i = 0; i < qtdConsulta; i++) {
                        try {
                            MaskFormatter mfCpf = new MaskFormatter("###.###.###-##");
                            mfCpf.setValueContainsLiteralCharacters(false);
                            consultas[i][3] = mfCpf.valueToString(consultas[i][3]);
                            consultas[i][5] = mfCpf.valueToString(consultas[i][5]);
                        } catch (ParseException p) {
                            lblSaida.setText("Ocorreu um erro na formatação do cpf,data ou horário");
                        }
                        String[] data = consultas[i][0].split("-");
                        consultas[i][0] = data[2] + "/" + data[1] + "/" + data[0];

                        consultas[i][1] = consultas[i][1].substring(0, 5);

                        Object[] dados = {consultas[i][0], consultas[i][1], consultas[i][2], consultas[i][3], consultas[i][4], consultas[i][5]};
                        tblConsultas1.addRow(dados);
                    }
                    lblSaida.setText("Dados encontrados");
                } else {
                    lblSaida.setText("Não existem consultas neste intervalo de tempo");
                }
            } else {
                lblSaida.setText("Intervalo entre datas inválido");
            }
        } catch (DateTimeParseException e) {
            lblSaida.setText("Datas inválidas");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JLabel lblBuscarDataFinal;
    private javax.swing.JLabel lblBuscarDataInicial;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JTable tblConsultas;
    private javax.swing.JFormattedTextField txtBuscarDataFinal;
    private javax.swing.JFormattedTextField txtBuscarDataInicial;
    // End of variables declaration//GEN-END:variables
}
