package br.com.fisioterapia.jframe.buscar;

import br.com.fisioterapia.database.anamnese.Tabagismo;
import br.com.fisioterapia.database.anamnese.Etilista;
import br.com.fisioterapia.database.anamnese.Cirurgia;
import br.com.fisioterapia.database.anamnese.Anamnese;
import br.com.fisioterapia.database.pessoas.Paciente;
import br.com.fisioterapia.jframe.cadastro.AnamneseJF;
import java.beans.PropertyVetoException;
import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class BuscarAnamneseJF extends javax.swing.JInternalFrame {
  
  
    /**
     * Creates new form AnamneseJF
     */
    public BuscarAnamneseJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTabagista = new javax.swing.ButtonGroup();
        btnGroupExTabagista = new javax.swing.ButtonGroup();
        btnGroupEtilista = new javax.swing.ButtonGroup();
        btnGroupExEtilista = new javax.swing.ButtonGroup();
        lblBuscaCpf = new javax.swing.JLabel();
        txtDoencasPrevias = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblTabagistaTitulo = new javax.swing.JLabel();
        lblPacienteTitulo = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblImcTitulo = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblTipoTabagismo = new javax.swing.JLabel();
        lblDataTabajista = new javax.swing.JLabel();
        txtTipoEtilista = new javax.swing.JTextField();
        lblTituloDoencasInfancia = new javax.swing.JLabel();
        lblTipoEtilista = new javax.swing.JLabel();
        lblEtilistaData = new javax.swing.JLabel();
        lblEtilistaTitulo = new javax.swing.JLabel();
        lblTituloCirurgiaPrevia = new javax.swing.JLabel();
        lblTituloDoencasPrevias = new javax.swing.JLabel();
        txtCausaCirurgia = new javax.swing.JTextField();
        lblDataCirurgia = new javax.swing.JLabel();
        txtCpfBusca = new javax.swing.JFormattedTextField();
        lblCausaCirurgia = new javax.swing.JLabel();
        txtLocalCirurgia = new javax.swing.JTextField();
        lblLocalCirurgia = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        lblSaida = new javax.swing.JLabel();
        txtDataTabagista = new javax.swing.JFormattedTextField();
        txtDataEtilista = new javax.swing.JFormattedTextField();
        txtDataCirurgia = new javax.swing.JFormattedTextField();
        spnAltura = new javax.swing.JSpinner();
        spnPeso = new javax.swing.JSpinner();
        txtTipoTabagismo = new javax.swing.JTextField();
        txtDoencasInfancia = new javax.swing.JTextField();
        txtTabagismoStatus = new javax.swing.JTextField();
        txtEtilistaStatus = new javax.swing.JTextField();
        txtPacienteNome = new javax.swing.JTextField();
        txtImc = new javax.swing.JTextField();
        txtCirurgiaStatus = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Anamnese");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 700));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblBuscaCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscaCpf.setText("CPF do Paciente:");
        getContentPane().add(lblBuscaCpf);
        lblBuscaCpf.setBounds(10, 20, 110, 20);

        txtDoencasPrevias.setEditable(false);
        getContentPane().add(txtDoencasPrevias);
        txtDoencasPrevias.setBounds(10, 400, 750, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(260, 20, 80, 30);

        lblTabagistaTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTabagistaTitulo.setText("Tabagista:");
        getContentPane().add(lblTabagistaTitulo);
        lblTabagistaTitulo.setBounds(10, 120, 80, 20);

        lblPacienteTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPacienteTitulo.setText("Paciente:");
        getContentPane().add(lblPacienteTitulo);
        lblPacienteTitulo.setBounds(370, 20, 60, 30);

        lblAltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltura.setText("Altura(m):");
        lblAltura.setToolTipText("");
        getContentPane().add(lblAltura);
        lblAltura.setBounds(200, 60, 70, 30);

        lblImcTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblImcTitulo.setText("IMC:");
        lblImcTitulo.setToolTipText("");
        getContentPane().add(lblImcTitulo);
        lblImcTitulo.setBounds(380, 60, 30, 30);

        lblPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPeso.setText("Peso(Kg):");
        getContentPane().add(lblPeso);
        lblPeso.setBounds(20, 60, 60, 30);

        lblTipoTabagismo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipoTabagismo.setText("Tipo:");
        getContentPane().add(lblTipoTabagismo);
        lblTipoTabagismo.setBounds(480, 140, 40, 30);

        lblDataTabajista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDataTabajista.setText("Desde:");
        getContentPane().add(lblDataTabajista);
        lblDataTabajista.setBounds(260, 150, 40, 20);

        txtTipoEtilista.setEditable(false);
        getContentPane().add(txtTipoEtilista);
        txtTipoEtilista.setBounds(520, 200, 120, 30);

        lblTituloDoencasInfancia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloDoencasInfancia.setText("Doenças da Infância:");
        getContentPane().add(lblTituloDoencasInfancia);
        lblTituloDoencasInfancia.setBounds(10, 260, 140, 20);

        lblTipoEtilista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipoEtilista.setText("Tipo:");
        getContentPane().add(lblTipoEtilista);
        lblTipoEtilista.setBounds(480, 200, 40, 30);

        lblEtilistaData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEtilistaData.setText("Desde:");
        getContentPane().add(lblEtilistaData);
        lblEtilistaData.setBounds(260, 210, 40, 20);

        lblEtilistaTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEtilistaTitulo.setText("Etilista:");
        getContentPane().add(lblEtilistaTitulo);
        lblEtilistaTitulo.setBounds(10, 180, 80, 20);

        lblTituloCirurgiaPrevia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloCirurgiaPrevia.setText("Cirurgia Prévia:");
        getContentPane().add(lblTituloCirurgiaPrevia);
        lblTituloCirurgiaPrevia.setBounds(10, 470, 140, 20);

        lblTituloDoencasPrevias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloDoencasPrevias.setText("Doenças Prévias:");
        getContentPane().add(lblTituloDoencasPrevias);
        lblTituloDoencasPrevias.setBounds(10, 350, 140, 30);

        txtCausaCirurgia.setEditable(false);
        getContentPane().add(txtCausaCirurgia);
        txtCausaCirurgia.setBounds(60, 540, 240, 30);

        lblDataCirurgia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDataCirurgia.setText("Data:");
        getContentPane().add(lblDataCirurgia);
        lblDataCirurgia.setBounds(320, 540, 40, 20);

        try {
            txtCpfBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfBusca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpfBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfBusca);
        txtCpfBusca.setBounds(120, 20, 110, 30);

        lblCausaCirurgia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCausaCirurgia.setText("Causa:");
        getContentPane().add(lblCausaCirurgia);
        lblCausaCirurgia.setBounds(10, 540, 40, 20);

        txtLocalCirurgia.setEditable(false);
        getContentPane().add(txtLocalCirurgia);
        txtLocalCirurgia.setBounds(560, 540, 200, 30);

        lblLocalCirurgia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLocalCirurgia.setText("Local:");
        getContentPane().add(lblLocalCirurgia);
        lblLocalCirurgia.setBounds(520, 540, 35, 20);

        btnInserir.setText("Inserir");
        getContentPane().add(btnInserir);
        btnInserir.setBounds(310, 840, 90, 23);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(10, 590, 750, 20);

        txtDataTabagista.setEditable(false);
        try {
            txtDataTabagista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataTabagista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataTabagista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataTabagistaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataTabagista);
        txtDataTabagista.setBounds(340, 140, 90, 30);

        txtDataEtilista.setEditable(false);
        try {
            txtDataEtilista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataEtilista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataEtilista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataEtilistaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataEtilista);
        txtDataEtilista.setBounds(340, 200, 90, 30);

        txtDataCirurgia.setEditable(false);
        try {
            txtDataCirurgia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCirurgia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataCirurgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataCirurgiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataCirurgia);
        txtDataCirurgia.setBounds(360, 540, 90, 30);

        spnAltura.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.1f));
        spnAltura.setEnabled(false);
        spnAltura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnAlturaStateChanged(evt);
            }
        });
        getContentPane().add(spnAltura);
        spnAltura.setBounds(270, 60, 50, 30);

        spnPeso.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        spnPeso.setEnabled(false);
        spnPeso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnPesoStateChanged(evt);
            }
        });
        getContentPane().add(spnPeso);
        spnPeso.setBounds(90, 60, 50, 30);

        txtTipoTabagismo.setEditable(false);
        getContentPane().add(txtTipoTabagismo);
        txtTipoTabagismo.setBounds(520, 140, 120, 30);

        txtDoencasInfancia.setEditable(false);
        getContentPane().add(txtDoencasInfancia);
        txtDoencasInfancia.setBounds(10, 300, 750, 30);

        txtTabagismoStatus.setEditable(false);
        getContentPane().add(txtTabagismoStatus);
        txtTabagismoStatus.setBounds(10, 140, 230, 30);

        txtEtilistaStatus.setEditable(false);
        getContentPane().add(txtEtilistaStatus);
        txtEtilistaStatus.setBounds(10, 200, 230, 30);

        txtPacienteNome.setEditable(false);
        getContentPane().add(txtPacienteNome);
        txtPacienteNome.setBounds(440, 20, 290, 30);

        txtImc.setEditable(false);
        getContentPane().add(txtImc);
        txtImc.setBounds(410, 60, 50, 30);

        txtCirurgiaStatus.setEditable(false);
        getContentPane().add(txtCirurgiaStatus);
        txtCirurgiaStatus.setBounds(10, 500, 240, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cpfB1[] = txtCpfBusca.getText().split("-");
        String cpfB2[] = cpfB1[0].split("\\.");
        String testeCpfB = cpfB2[0] + cpfB2[1] + cpfB2[2] + cpfB1[1];
        long cpfB;

        if (!testeCpfB.isBlank()) {
            cpfB = Long.parseLong(testeCpfB);
            Paciente p1 = new Paciente(cpfB);
            if (Anamnese.verificarAnamnese(cpfB)) {//Verificar se o paciente possui alguma anamnese
                p1 = Paciente.BuscarPaciente(cpfB);
                txtPacienteNome.setText(p1.getNome());
                Anamnese a1 = Anamnese.buscarAnamneseIdPessoa(p1.getCodPessoa());
                spnPeso.setValue(a1.getPeso());
                spnAltura.setValue(a1.getAltura());
                txtDoencasInfancia.setText(a1.getDoencaInfancia());
                txtDoencasPrevias.setText(a1.getDoencaPrevia());
                ///Tabagismo
                if (a1.getTabagista().equals("Nunca")) {
                    lblDataTabajista.setVisible(false);
                    txtDataTabagista.setVisible(false);
                    lblTipoTabagismo.setVisible(false);
                    txtTipoTabagismo.setVisible(false);
                    txtTabagismoStatus.setText("Nunca fumou");
                } else if (a1.getTabagista().equals("Sim")) {
                    Tabagismo t1 = Tabagismo.buscarTabagismoIdAnamnese(a1.getIdAnamnese());
                    lblDataTabajista.setVisible(true);
                    txtDataTabagista.setVisible(true);
                    lblTipoTabagismo.setVisible(true);
                    txtTipoTabagismo.setVisible(true);
                    txtDataTabagista.setText(t1.getDataTabagismo().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                    txtTipoTabagismo.setText(t1.getTipo());
                    txtTabagismoStatus.setText("Fumante");
                } else if (a1.getTabagista().equals("Não")) {
                    Tabagismo t1 = Tabagismo.buscarTabagismoIdAnamnese(a1.getIdAnamnese());
                    lblDataTabajista.setVisible(true);
                    txtDataTabagista.setVisible(true);
                    lblTipoTabagismo.setVisible(true);
                    txtTipoTabagismo.setVisible(true);
                    txtDataTabagista.setText(t1.getDataTabagismo().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                    txtTipoTabagismo.setText(t1.getTipo());
                    txtTabagismoStatus.setText("Ex-fumante");
                }
                ///Etilismo
                if (a1.getEtilista().equals("Nunca")) {
                    lblEtilistaData.setVisible(false);
                    txtDataEtilista.setVisible(false);
                    lblTipoEtilista.setVisible(false);
                    txtTipoEtilista.setVisible(false);
                    txtEtilistaStatus.setText("Nunca bebeu");
                } else if (a1.getEtilista().equals("Sim")) {
                    Etilista e1 = Etilista.buscarEtilistaIdAnamnese(a1.getIdAnamnese());
                    lblEtilistaData.setVisible(true);
                    txtDataEtilista.setVisible(true);
                    lblTipoEtilista.setVisible(true);
                    txtTipoEtilista.setVisible(true);
                    txtDataEtilista.setText(e1.getDataEtilista().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                    txtTipoEtilista.setText(e1.getTipo());
                    txtEtilistaStatus.setText("Consome bebidas alcoólicas");
                } else if (a1.getEtilista().equals("Não")) {
                    Etilista e1 = Etilista.buscarEtilistaIdAnamnese(a1.getIdAnamnese());
                    lblEtilistaData.setVisible(true);
                    txtDataEtilista.setVisible(true);
                    lblTipoEtilista.setVisible(true);
                    txtTipoEtilista.setVisible(true);
                    txtDataEtilista.setText(e1.getDataEtilista().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                    txtTipoEtilista.setText(e1.getTipo());
                    txtEtilistaStatus.setText("Parou de beber");
                }
                ///Cirurgia:
                if (a1.verificarCirurgia()) {
                    Cirurgia c1 = Cirurgia.buscarCirurgiaIdAnamnese(a1.getIdAnamnese());
                    lblCausaCirurgia.setVisible(true);
                    txtCausaCirurgia.setVisible(true);
                    lblDataCirurgia.setVisible(true);
                    txtDataCirurgia.setVisible(true);
                    lblLocalCirurgia.setVisible(true);
                    txtLocalCirurgia.setVisible(true);
                    txtCausaCirurgia.setText(c1.getCausa());
                    txtDataCirurgia.setText(c1.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                    txtLocalCirurgia.setText(c1.getLocal());
                    txtCirurgiaStatus.setText("Dados da cirurgia:");
                } else {
                    lblCausaCirurgia.setVisible(false);
                    txtCausaCirurgia.setVisible(false);
                    lblDataCirurgia.setVisible(false);
                    txtDataCirurgia.setVisible(false);
                    lblLocalCirurgia.setVisible(false);
                    txtLocalCirurgia.setVisible(false);
                    txtCirurgiaStatus.setText("Não possui cirurgia prévia");
                }
                lblSaida.setText("Anamnese encontrada");
            } else {
                lblSaida.setText("Não foi encontrada uma anamnese para o paciente com esse cpf");
            }
        } else {
            lblSaida.setText("Campo em branco");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCpfBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfBuscaActionPerformed

    private void txtDataTabagistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataTabagistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataTabagistaActionPerformed

    private void txtDataEtilistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataEtilistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataEtilistaActionPerformed

    private void txtDataCirurgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCirurgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataCirurgiaActionPerformed

    private void spnPesoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnPesoStateChanged
        float peso = (float) spnPeso.getValue();
        float altura = (float) spnAltura.getValue();
        float imc1;
        if (altura > 0) {
            imc1 = peso / (altura * altura);
            String imc = String.format("%.1f", imc1);
            txtImc.setText(imc);
        } else {
            txtImc.setText(Float.toString(0));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_spnPesoStateChanged

    private void spnAlturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnAlturaStateChanged
        float peso = (float) spnPeso.getValue();
        float altura = (float) spnAltura.getValue();
        float imc1;
        if (altura > 0) {
            imc1 = peso / (altura * altura);
            String imc = String.format("%.1f", imc1);
            txtImc.setText(imc);
        } else {
            txtImc.setText(Float.toString(0));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_spnAlturaStateChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btnGroupEtilista;
    private javax.swing.ButtonGroup btnGroupExEtilista;
    private javax.swing.ButtonGroup btnGroupExTabagista;
    private javax.swing.ButtonGroup btnGroupTabagista;
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblBuscaCpf;
    private javax.swing.JLabel lblCausaCirurgia;
    private javax.swing.JLabel lblDataCirurgia;
    private javax.swing.JLabel lblDataTabajista;
    private javax.swing.JLabel lblEtilistaData;
    private javax.swing.JLabel lblEtilistaTitulo;
    private javax.swing.JLabel lblImcTitulo;
    private javax.swing.JLabel lblLocalCirurgia;
    private javax.swing.JLabel lblPacienteTitulo;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblTabagistaTitulo;
    private javax.swing.JLabel lblTipoEtilista;
    private javax.swing.JLabel lblTipoTabagismo;
    private javax.swing.JLabel lblTituloCirurgiaPrevia;
    private javax.swing.JLabel lblTituloDoencasInfancia;
    private javax.swing.JLabel lblTituloDoencasPrevias;
    private javax.swing.JSpinner spnAltura;
    private javax.swing.JSpinner spnPeso;
    private javax.swing.JTextField txtCausaCirurgia;
    private javax.swing.JTextField txtCirurgiaStatus;
    private javax.swing.JFormattedTextField txtCpfBusca;
    private javax.swing.JFormattedTextField txtDataCirurgia;
    private javax.swing.JFormattedTextField txtDataEtilista;
    private javax.swing.JFormattedTextField txtDataTabagista;
    private javax.swing.JTextField txtDoencasInfancia;
    private javax.swing.JTextField txtDoencasPrevias;
    private javax.swing.JTextField txtEtilistaStatus;
    private javax.swing.JTextField txtImc;
    private javax.swing.JTextField txtLocalCirurgia;
    private javax.swing.JTextField txtPacienteNome;
    private javax.swing.JTextField txtTabagismoStatus;
    private javax.swing.JTextField txtTipoEtilista;
    private javax.swing.JTextField txtTipoTabagismo;
    // End of variables declaration//GEN-END:variables
}
