package br.com.fisioterapia.jframe.cadastro;

import br.com.fisioterapia.database.anamnese.Tabagismo;
import br.com.fisioterapia.database.anamnese.Etilista;
import br.com.fisioterapia.database.anamnese.Cirurgia;
import br.com.fisioterapia.database.anamnese.Anamnese;
import br.com.fisioterapia.database.pessoas.Paciente;
import java.beans.PropertyVetoException;
import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class AnamneseJF extends javax.swing.JInternalFrame {

    private static int idPessoa = 0;

    public static int getIdPessoa() {
        return idPessoa;
    }

    public static void setIdPessoa(int idPessoa) {
        AnamneseJF.idPessoa = idPessoa;
    }

    /**
     * Creates new form AnamneseJF
     */
    public AnamneseJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTabagista = new javax.swing.ButtonGroup();
        btnGroupExTabagista = new javax.swing.ButtonGroup();
        btnGroupEtilista = new javax.swing.ButtonGroup();
        btnGroupExEtilista = new javax.swing.ButtonGroup();
        lblBuscaCpf = new javax.swing.JLabel();
        txtTipoTabagismo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblTabagistaTitulo = new javax.swing.JLabel();
        lblPacienteTitulo = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblImcTitulo = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        btnNuncaTabagista = new javax.swing.JRadioButton();
        btnSimTabagista = new javax.swing.JRadioButton();
        lblTipoTabagismo = new javax.swing.JLabel();
        lblDataTabajista = new javax.swing.JLabel();
        txtTipoEtilista = new javax.swing.JTextField();
        lblTituloDoencasInfancia = new javax.swing.JLabel();
        btnEtilistaNunca = new javax.swing.JRadioButton();
        btnEtilistaSim = new javax.swing.JRadioButton();
        lblTipoEtilista = new javax.swing.JLabel();
        lblEtilistaData = new javax.swing.JLabel();
        lblEtilistaTitulo = new javax.swing.JLabel();
        btnCatapora = new javax.swing.JRadioButton();
        btnSarampo = new javax.swing.JRadioButton();
        btnRubeola = new javax.swing.JRadioButton();
        btnCaxumba = new javax.swing.JRadioButton();
        btnNenhumaCirurgiaPrevia = new javax.swing.JRadioButton();
        btnCoqueluche = new javax.swing.JRadioButton();
        btnEscarlatina = new javax.swing.JRadioButton();
        txtQuaisDoencasInfancia = new javax.swing.JTextField();
        lblTituloQuaisDoencasInfancia = new javax.swing.JLabel();
        lblTituloCirurgiaPrevia = new javax.swing.JLabel();
        btnParkinson = new javax.swing.JRadioButton();
        btnAvc = new javax.swing.JRadioButton();
        btnHipertensaoArterial = new javax.swing.JRadioButton();
        btnDiabetesMellitus = new javax.swing.JRadioButton();
        btnOutrasDoencasPrevias = new javax.swing.JRadioButton();
        btnAlzheimer = new javax.swing.JRadioButton();
        btnDemencia = new javax.swing.JRadioButton();
        txtQuaisDoencasPrevias = new javax.swing.JTextField();
        lblTituloQuaisDoencasPrevias = new javax.swing.JLabel();
        btnTremor = new javax.swing.JRadioButton();
        btnPerdaVisual = new javax.swing.JRadioButton();
        btnSifilis = new javax.swing.JRadioButton();
        btnPerdaPeso = new javax.swing.JRadioButton();
        btnPerdaAuditiva = new javax.swing.JRadioButton();
        btnOsteomelite = new javax.swing.JRadioButton();
        btnHipercolesterolemia = new javax.swing.JRadioButton();
        btnIncontinenciaFecal = new javax.swing.JRadioButton();
        btnIncontinenciaUrinaria = new javax.swing.JRadioButton();
        btnDisturbioComportamental = new javax.swing.JRadioButton();
        btnTuberculose = new javax.swing.JRadioButton();
        btnDoencaChagas = new javax.swing.JRadioButton();
        btnHepatite = new javax.swing.JRadioButton();
        btnAsma = new javax.swing.JRadioButton();
        btnEfisema = new javax.swing.JRadioButton();
        btnDepressao = new javax.swing.JRadioButton();
        btnAnsiedade = new javax.swing.JRadioButton();
        btnSindromePanico = new javax.swing.JRadioButton();
        btnArtriteReumatoide = new javax.swing.JRadioButton();
        btnGota = new javax.swing.JRadioButton();
        btnArtrose = new javax.swing.JRadioButton();
        btnTonteira = new javax.swing.JRadioButton();
        btnEsquecimento = new javax.swing.JRadioButton();
        lblTituloDoencasPrevias = new javax.swing.JLabel();
        txtCausaCirurgia = new javax.swing.JTextField();
        lblDataCirurgia = new javax.swing.JLabel();
        txtCpfBusca = new javax.swing.JFormattedTextField();
        lblCausaCirurgia = new javax.swing.JLabel();
        txtLocalCirurgia = new javax.swing.JTextField();
        lblLocalCirurgia = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        lblSaida = new javax.swing.JLabel();
        btnOutrasDoencasInfancia = new javax.swing.JRadioButton();
        btnNenhumaDoencaInfancia = new javax.swing.JRadioButton();
        btnNenhumaDoencaPrevia = new javax.swing.JRadioButton();
        btnCadastrar = new javax.swing.JButton();
        btnNaoTabagista = new javax.swing.JRadioButton();
        btnEtilistaNao = new javax.swing.JRadioButton();
        txtDataTabagista = new javax.swing.JFormattedTextField();
        txtDataEtilista = new javax.swing.JFormattedTextField();
        txtDataCirurgia = new javax.swing.JFormattedTextField();
        spnAltura = new javax.swing.JSpinner();
        spnPeso = new javax.swing.JSpinner();
        txtImc = new javax.swing.JTextField();
        txtPacienteNome = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Anamnese");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 700));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblBuscaCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBuscaCpf.setText("CPF do Paciente:");
        getContentPane().add(lblBuscaCpf);
        lblBuscaCpf.setBounds(10, 20, 110, 20);
        getContentPane().add(txtTipoTabagismo);
        txtTipoTabagismo.setBounds(520, 120, 120, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(260, 20, 80, 30);

        lblTabagistaTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTabagistaTitulo.setText("Tabagista:");
        getContentPane().add(lblTabagistaTitulo);
        lblTabagistaTitulo.setBounds(10, 110, 80, 20);

        lblPacienteTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPacienteTitulo.setText("Paciente:");
        getContentPane().add(lblPacienteTitulo);
        lblPacienteTitulo.setBounds(370, 20, 60, 30);

        lblAltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltura.setText("Altura(m):");
        lblAltura.setToolTipText("");
        getContentPane().add(lblAltura);
        lblAltura.setBounds(200, 60, 70, 30);

        lblImcTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblImcTitulo.setText("IMC:");
        lblImcTitulo.setToolTipText("");
        getContentPane().add(lblImcTitulo);
        lblImcTitulo.setBounds(370, 60, 30, 30);

        lblPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPeso.setText("Peso(Kg):");
        getContentPane().add(lblPeso);
        lblPeso.setBounds(10, 60, 60, 30);

        btnGroupTabagista.add(btnNuncaTabagista);
        btnNuncaTabagista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNuncaTabagista.setText("Nunca");
        btnNuncaTabagista.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnNuncaTabagistaStateChanged(evt);
            }
        });
        getContentPane().add(btnNuncaTabagista);
        btnNuncaTabagista.setBounds(110, 130, 70, 23);

        btnGroupTabagista.add(btnSimTabagista);
        btnSimTabagista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSimTabagista.setText("Sim");
        getContentPane().add(btnSimTabagista);
        btnSimTabagista.setBounds(10, 130, 50, 23);

        lblTipoTabagismo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipoTabagismo.setText("Tipo:");
        getContentPane().add(lblTipoTabagismo);
        lblTipoTabagismo.setBounds(480, 120, 40, 30);

        lblDataTabajista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDataTabajista.setText("Desde:");
        getContentPane().add(lblDataTabajista);
        lblDataTabajista.setBounds(260, 120, 40, 40);
        getContentPane().add(txtTipoEtilista);
        txtTipoEtilista.setBounds(520, 190, 120, 30);

        lblTituloDoencasInfancia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloDoencasInfancia.setText("Doenças da Infância:");
        getContentPane().add(lblTituloDoencasInfancia);
        lblTituloDoencasInfancia.setBounds(10, 240, 140, 20);

        btnGroupEtilista.add(btnEtilistaNunca);
        btnEtilistaNunca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEtilistaNunca.setText("Nunca");
        btnEtilistaNunca.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnEtilistaNuncaStateChanged(evt);
            }
        });
        getContentPane().add(btnEtilistaNunca);
        btnEtilistaNunca.setBounds(110, 200, 60, 23);

        btnGroupEtilista.add(btnEtilistaSim);
        btnEtilistaSim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEtilistaSim.setText("Sim");
        getContentPane().add(btnEtilistaSim);
        btnEtilistaSim.setBounds(10, 200, 50, 23);

        lblTipoEtilista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipoEtilista.setText("Tipo:");
        getContentPane().add(lblTipoEtilista);
        lblTipoEtilista.setBounds(480, 190, 40, 30);

        lblEtilistaData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEtilistaData.setText("Desde:");
        getContentPane().add(lblEtilistaData);
        lblEtilistaData.setBounds(260, 200, 40, 20);

        lblEtilistaTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEtilistaTitulo.setText("Etilista:");
        getContentPane().add(lblEtilistaTitulo);
        lblEtilistaTitulo.setBounds(10, 180, 80, 20);

        btnCatapora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCatapora.setText("Catapora");
        btnCatapora.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnCataporaStateChanged(evt);
            }
        });
        getContentPane().add(btnCatapora);
        btnCatapora.setBounds(90, 260, 80, 23);

        btnSarampo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSarampo.setText("Sarampo");
        btnSarampo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnSarampoStateChanged(evt);
            }
        });
        getContentPane().add(btnSarampo);
        btnSarampo.setBounds(10, 260, 80, 23);

        btnRubeola.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRubeola.setText("Rubéola");
        btnRubeola.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnRubeolaStateChanged(evt);
            }
        });
        btnRubeola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRubeolaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRubeola);
        btnRubeola.setBounds(310, 260, 80, 23);

        btnCaxumba.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCaxumba.setText("Caxumba (Parotidite)");
        btnCaxumba.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnCaxumbaStateChanged(evt);
            }
        });
        getContentPane().add(btnCaxumba);
        btnCaxumba.setBounds(170, 260, 140, 23);

        btnNenhumaCirurgiaPrevia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNenhumaCirurgiaPrevia.setText("Nenhuma ");
        btnNenhumaCirurgiaPrevia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnNenhumaCirurgiaPreviaStateChanged(evt);
            }
        });
        getContentPane().add(btnNenhumaCirurgiaPrevia);
        btnNenhumaCirurgiaPrevia.setBounds(10, 590, 90, 23);

        btnCoqueluche.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCoqueluche.setText("Coqueluche");
        btnCoqueluche.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnCoquelucheStateChanged(evt);
            }
        });
        getContentPane().add(btnCoqueluche);
        btnCoqueluche.setBounds(390, 260, 90, 23);

        btnEscarlatina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEscarlatina.setText("Escarlatina");
        btnEscarlatina.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnEscarlatinaStateChanged(evt);
            }
        });
        btnEscarlatina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscarlatinaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEscarlatina);
        btnEscarlatina.setBounds(480, 260, 100, 23);
        getContentPane().add(txtQuaisDoencasInfancia);
        txtQuaisDoencasInfancia.setBounds(130, 290, 240, 30);

        lblTituloQuaisDoencasInfancia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTituloQuaisDoencasInfancia.setText("Quais?");
        getContentPane().add(lblTituloQuaisDoencasInfancia);
        lblTituloQuaisDoencasInfancia.setBounds(90, 290, 40, 30);

        lblTituloCirurgiaPrevia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloCirurgiaPrevia.setText("Cirurgia Prévia:");
        getContentPane().add(lblTituloCirurgiaPrevia);
        lblTituloCirurgiaPrevia.setBounds(10, 530, 140, 20);

        btnParkinson.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnParkinson.setText("Parkinson");
        btnParkinson.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnParkinsonStateChanged(evt);
            }
        });
        getContentPane().add(btnParkinson);
        btnParkinson.setBounds(450, 410, 80, 23);

        btnAvc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAvc.setText("AVC");
        btnAvc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnAvcStateChanged(evt);
            }
        });
        getContentPane().add(btnAvc);
        btnAvc.setBounds(220, 380, 60, 23);

        btnHipertensaoArterial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHipertensaoArterial.setText("Hipertensão Arterial");
        btnHipertensaoArterial.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnHipertensaoArterialStateChanged(evt);
            }
        });
        getContentPane().add(btnHipertensaoArterial);
        btnHipertensaoArterial.setBounds(590, 350, 150, 23);

        btnDiabetesMellitus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDiabetesMellitus.setText("Diabetes Mellitus");
        btnDiabetesMellitus.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnDiabetesMellitusStateChanged(evt);
            }
        });
        getContentPane().add(btnDiabetesMellitus);
        btnDiabetesMellitus.setBounds(450, 350, 120, 23);

        btnOutrasDoencasPrevias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOutrasDoencasPrevias.setText("Outras");
        btnOutrasDoencasPrevias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnOutrasDoencasPreviasItemStateChanged(evt);
            }
        });
        btnOutrasDoencasPrevias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnOutrasDoencasPreviasStateChanged(evt);
            }
        });
        getContentPane().add(btnOutrasDoencasPrevias);
        btnOutrasDoencasPrevias.setBounds(10, 500, 80, 20);

        btnAlzheimer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAlzheimer.setText("Alzheimer");
        btnAlzheimer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnAlzheimerStateChanged(evt);
            }
        });
        getContentPane().add(btnAlzheimer);
        btnAlzheimer.setBounds(110, 350, 80, 23);

        btnDemencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDemencia.setText("Demência");
        btnDemencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnDemenciaStateChanged(evt);
            }
        });
        getContentPane().add(btnDemencia);
        btnDemencia.setBounds(220, 350, 80, 23);
        getContentPane().add(txtQuaisDoencasPrevias);
        txtQuaisDoencasPrevias.setBounds(130, 500, 240, 30);

        lblTituloQuaisDoencasPrevias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTituloQuaisDoencasPrevias.setText("Quais?");
        getContentPane().add(lblTituloQuaisDoencasPrevias);
        lblTituloQuaisDoencasPrevias.setBounds(90, 500, 40, 30);

        btnTremor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTremor.setText("Tremor");
        btnTremor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnTremorStateChanged(evt);
            }
        });
        getContentPane().add(btnTremor);
        btnTremor.setBounds(320, 350, 70, 23);

        btnPerdaVisual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPerdaVisual.setText("Perda visual");
        btnPerdaVisual.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnPerdaVisualStateChanged(evt);
            }
        });
        getContentPane().add(btnPerdaVisual);
        btnPerdaVisual.setBounds(10, 380, 89, 20);

        btnSifilis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSifilis.setText("Sifilis");
        btnSifilis.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnSifilisStateChanged(evt);
            }
        });
        getContentPane().add(btnSifilis);
        btnSifilis.setBounds(450, 440, 80, 23);

        btnPerdaPeso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPerdaPeso.setText("Perda de peso");
        btnPerdaPeso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnPerdaPesoStateChanged(evt);
            }
        });
        getContentPane().add(btnPerdaPeso);
        btnPerdaPeso.setBounds(10, 350, 110, 23);

        btnPerdaAuditiva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPerdaAuditiva.setText("Perda auditiva");
        btnPerdaAuditiva.setActionCommand("");
        btnPerdaAuditiva.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnPerdaAuditivaStateChanged(evt);
            }
        });
        getContentPane().add(btnPerdaAuditiva);
        btnPerdaAuditiva.setBounds(110, 380, 110, 23);

        btnOsteomelite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOsteomelite.setText("Osteomielite");
        btnOsteomelite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnOsteomeliteStateChanged(evt);
            }
        });
        getContentPane().add(btnOsteomelite);
        btnOsteomelite.setBounds(320, 380, 100, 23);

        btnHipercolesterolemia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHipercolesterolemia.setText("Hipercolesterolemia");
        btnHipercolesterolemia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnHipercolesterolemiaStateChanged(evt);
            }
        });
        getContentPane().add(btnHipercolesterolemia);
        btnHipercolesterolemia.setBounds(450, 380, 131, 23);

        btnIncontinenciaFecal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIncontinenciaFecal.setText("Incontinêncioa Fecal");
        btnIncontinenciaFecal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnIncontinenciaFecalStateChanged(evt);
            }
        });
        getContentPane().add(btnIncontinenciaFecal);
        btnIncontinenciaFecal.setBounds(590, 380, 140, 23);

        btnIncontinenciaUrinaria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIncontinenciaUrinaria.setText("Incontinência urinária");
        btnIncontinenciaUrinaria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnIncontinenciaUrinariaStateChanged(evt);
            }
        });
        getContentPane().add(btnIncontinenciaUrinaria);
        btnIncontinenciaUrinaria.setBounds(590, 410, 150, 20);

        btnDisturbioComportamental.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDisturbioComportamental.setText("Disturbio Comportamental");
        btnDisturbioComportamental.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnDisturbioComportamentalStateChanged(evt);
            }
        });
        getContentPane().add(btnDisturbioComportamental);
        btnDisturbioComportamental.setBounds(590, 440, 170, 23);

        btnTuberculose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTuberculose.setText("Tuberculose");
        btnTuberculose.setActionCommand("");
        btnTuberculose.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnTuberculoseStateChanged(evt);
            }
        });
        getContentPane().add(btnTuberculose);
        btnTuberculose.setBounds(10, 410, 100, 23);

        btnDoencaChagas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDoencaChagas.setText("Doença de Chagas");
        btnDoencaChagas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnDoencaChagasStateChanged(evt);
            }
        });
        getContentPane().add(btnDoencaChagas);
        btnDoencaChagas.setBounds(320, 470, 130, 23);

        btnHepatite.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHepatite.setText("Hepatite");
        btnHepatite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnHepatiteStateChanged(evt);
            }
        });
        getContentPane().add(btnHepatite);
        btnHepatite.setBounds(110, 410, 80, 23);

        btnAsma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAsma.setText("Asma");
        btnAsma.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnAsmaStateChanged(evt);
            }
        });
        getContentPane().add(btnAsma);
        btnAsma.setBounds(220, 410, 80, 23);

        btnEfisema.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEfisema.setText("Enfisema");
        btnEfisema.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnEfisemaStateChanged(evt);
            }
        });
        getContentPane().add(btnEfisema);
        btnEfisema.setBounds(10, 440, 89, 20);

        btnDepressao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDepressao.setText("Depressão");
        btnDepressao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnDepressaoStateChanged(evt);
            }
        });
        getContentPane().add(btnDepressao);
        btnDepressao.setBounds(220, 440, 90, 23);

        btnAnsiedade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAnsiedade.setText("Ansiedade");
        btnAnsiedade.setActionCommand("");
        btnAnsiedade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnAnsiedadeStateChanged(evt);
            }
        });
        getContentPane().add(btnAnsiedade);
        btnAnsiedade.setBounds(110, 440, 110, 23);

        btnSindromePanico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSindromePanico.setText("Sindrome do pânico");
        btnSindromePanico.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnSindromePanicoStateChanged(evt);
            }
        });
        getContentPane().add(btnSindromePanico);
        btnSindromePanico.setBounds(450, 470, 140, 23);

        btnArtriteReumatoide.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnArtriteReumatoide.setText("Artrite Reumatóide");
        btnArtriteReumatoide.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnArtriteReumatoideStateChanged(evt);
            }
        });
        getContentPane().add(btnArtriteReumatoide);
        btnArtriteReumatoide.setBounds(320, 440, 130, 23);

        btnGota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGota.setText("Gota");
        btnGota.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnGotaStateChanged(evt);
            }
        });
        getContentPane().add(btnGota);
        btnGota.setBounds(320, 410, 90, 23);

        btnArtrose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnArtrose.setText("Artrose");
        btnArtrose.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnArtroseStateChanged(evt);
            }
        });
        getContentPane().add(btnArtrose);
        btnArtrose.setBounds(10, 470, 89, 20);

        btnTonteira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTonteira.setText("Tonteira");
        btnTonteira.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnTonteiraStateChanged(evt);
            }
        });
        getContentPane().add(btnTonteira);
        btnTonteira.setBounds(220, 470, 100, 23);

        btnEsquecimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEsquecimento.setText("Esquecimento");
        btnEsquecimento.setActionCommand("");
        btnEsquecimento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnEsquecimentoStateChanged(evt);
            }
        });
        getContentPane().add(btnEsquecimento);
        btnEsquecimento.setBounds(110, 470, 110, 23);

        lblTituloDoencasPrevias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloDoencasPrevias.setText("Doenças Prévias:");
        getContentPane().add(lblTituloDoencasPrevias);
        lblTituloDoencasPrevias.setBounds(10, 320, 140, 30);
        getContentPane().add(txtCausaCirurgia);
        txtCausaCirurgia.setBounds(50, 560, 240, 30);

        lblDataCirurgia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDataCirurgia.setText("Data:");
        getContentPane().add(lblDataCirurgia);
        lblDataCirurgia.setBounds(320, 560, 40, 20);

        try {
            txtCpfBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfBusca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpfBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfBusca);
        txtCpfBusca.setBounds(120, 20, 110, 30);

        lblCausaCirurgia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCausaCirurgia.setText("Causa:");
        getContentPane().add(lblCausaCirurgia);
        lblCausaCirurgia.setBounds(10, 560, 40, 20);
        getContentPane().add(txtLocalCirurgia);
        txtLocalCirurgia.setBounds(560, 560, 200, 30);

        lblLocalCirurgia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLocalCirurgia.setText("Local:");
        getContentPane().add(lblLocalCirurgia);
        lblLocalCirurgia.setBounds(520, 560, 35, 20);

        btnInserir.setText("Inserir");
        getContentPane().add(btnInserir);
        btnInserir.setBounds(310, 840, 90, 23);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(10, 640, 750, 20);

        btnOutrasDoencasInfancia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOutrasDoencasInfancia.setText("Outras");
        btnOutrasDoencasInfancia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnOutrasDoencasInfanciaStateChanged(evt);
            }
        });
        getContentPane().add(btnOutrasDoencasInfancia);
        btnOutrasDoencasInfancia.setBounds(10, 290, 80, 23);

        btnNenhumaDoencaInfancia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNenhumaDoencaInfancia.setText("Nenhuma");
        btnNenhumaDoencaInfancia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnNenhumaDoencaInfanciaStateChanged(evt);
            }
        });
        getContentPane().add(btnNenhumaDoencaInfancia);
        btnNenhumaDoencaInfancia.setBounds(580, 260, 80, 23);

        btnNenhumaDoencaPrevia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNenhumaDoencaPrevia.setText("Nenhuma");
        btnNenhumaDoencaPrevia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnNenhumaDoencaPreviaStateChanged(evt);
            }
        });
        getContentPane().add(btnNenhumaDoencaPrevia);
        btnNenhumaDoencaPrevia.setBounds(590, 470, 80, 23);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(340, 600, 90, 30);

        btnGroupTabagista.add(btnNaoTabagista);
        btnNaoTabagista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNaoTabagista.setText("Não");
        getContentPane().add(btnNaoTabagista);
        btnNaoTabagista.setBounds(60, 130, 50, 23);

        btnGroupEtilista.add(btnEtilistaNao);
        btnEtilistaNao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEtilistaNao.setText("Não");
        getContentPane().add(btnEtilistaNao);
        btnEtilistaNao.setBounds(60, 200, 50, 23);

        try {
            txtDataTabagista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataTabagista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataTabagista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataTabagistaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataTabagista);
        txtDataTabagista.setBounds(340, 120, 90, 30);

        try {
            txtDataEtilista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataEtilista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataEtilista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataEtilistaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataEtilista);
        txtDataEtilista.setBounds(340, 190, 90, 30);

        try {
            txtDataCirurgia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCirurgia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataCirurgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataCirurgiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataCirurgia);
        txtDataCirurgia.setBounds(360, 560, 90, 30);

        spnAltura.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.1f));
        spnAltura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnAlturaStateChanged(evt);
            }
        });
        getContentPane().add(spnAltura);
        spnAltura.setBounds(270, 60, 50, 30);

        spnPeso.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        spnPeso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnPesoStateChanged(evt);
            }
        });
        getContentPane().add(spnPeso);
        spnPeso.setBounds(80, 60, 50, 30);

        txtImc.setEditable(false);
        getContentPane().add(txtImc);
        txtImc.setBounds(430, 60, 50, 30);

        txtPacienteNome.setEditable(false);
        getContentPane().add(txtPacienteNome);
        txtPacienteNome.setBounds(430, 20, 330, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cpfB1[] = txtCpfBusca.getText().split("-");
        String cpfB2[] = cpfB1[0].split("\\.");
        String testeCpfB = cpfB2[0] + cpfB2[1] + cpfB2[2] + cpfB1[1];
        long cpfB;

        if (!testeCpfB.isBlank()) {
            cpfB = Long.parseLong(testeCpfB);
            Paciente p1 = new Paciente(cpfB);
            if (p1.verificarCpf()) {
                p1 = Paciente.BuscarPaciente(cpfB);
                txtPacienteNome.setText(p1.getNome());
                AnamneseJF.setIdPessoa(p1.getCodPessoa());
                lblSaida.setText("Paciente encontrado");
            } else {
                lblSaida.setText("Cpf não encontrado");
            }
        } else {
            lblSaida.setText("Campo em branco");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRubeolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRubeolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRubeolaActionPerformed

    private void txtCpfBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfBuscaActionPerformed

    private void txtDataTabagistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataTabagistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataTabagistaActionPerformed

    private void txtDataEtilistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataEtilistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataEtilistaActionPerformed

    private void txtDataCirurgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCirurgiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataCirurgiaActionPerformed

    private void spnPesoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnPesoStateChanged
        float peso = (float) spnPeso.getValue();
        float altura = (float) spnAltura.getValue();
        float imc1;
        if (altura > 0) {
            imc1 = peso / (altura * altura);
            String imc = String.format("%.1f", imc1);
            txtImc.setText(imc);
        } else {
            txtImc.setText(Float.toString(0));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_spnPesoStateChanged

    private void spnAlturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnAlturaStateChanged
        float peso = (float) spnPeso.getValue();
        float altura = (float) spnAltura.getValue();
        float imc1;
        if (altura > 0) {
            imc1 = peso / (altura * altura);
            String imc = String.format("%.1f", imc1);
            txtImc.setText(imc);
        } else {
            txtImc.setText(Float.toString(0));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_spnAlturaStateChanged

    private void btnOutrasDoencasPreviasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnOutrasDoencasPreviasItemStateChanged
        if (btnOutrasDoencasPrevias.isSelected()) {
            txtQuaisDoencasPrevias.setVisible(true);
            lblTituloQuaisDoencasPrevias.setVisible(true);
        } else {
            txtQuaisDoencasPrevias.setVisible(false);
            lblTituloQuaisDoencasPrevias.setVisible(false);
        }
        btnNenhumaDoencaInfancia.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOutrasDoencasPreviasItemStateChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        txtQuaisDoencasInfancia.setVisible(false);
        lblTituloQuaisDoencasInfancia.setVisible(false);
        txtQuaisDoencasPrevias.setVisible(false);
        lblTituloQuaisDoencasPrevias.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnNuncaTabagistaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnNuncaTabagistaStateChanged
        if (btnNuncaTabagista.isSelected()) {
            lblDataTabajista.setVisible(false);
            txtDataTabagista.setVisible(false);
            lblTipoTabagismo.setVisible(false);
            txtTipoTabagismo.setVisible(false);
        } else {
            lblDataTabajista.setVisible(true);
            txtDataTabagista.setVisible(true);
            lblTipoTabagismo.setVisible(true);
            txtTipoTabagismo.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuncaTabagistaStateChanged

    private void btnEtilistaNuncaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnEtilistaNuncaStateChanged
        if (btnEtilistaNunca.isSelected()) {
            lblEtilistaData.setVisible(false);
            txtDataEtilista.setVisible(false);
            lblTipoEtilista.setVisible(false);
            txtTipoEtilista.setVisible(false);
        } else {
            lblEtilistaData.setVisible(true);
            txtDataEtilista.setVisible(true);
            lblTipoEtilista.setVisible(true);
            txtTipoEtilista.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEtilistaNuncaStateChanged

    private void btnNenhumaDoencaInfanciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnNenhumaDoencaInfanciaStateChanged
        if (btnNenhumaDoencaInfancia.isSelected()) {
            btnSarampo.setSelected(false);
            btnCatapora.setSelected(false);
            btnCaxumba.setSelected(false);
            btnRubeola.setSelected(false);
            btnCoqueluche.setSelected(false);
            btnEscarlatina.setSelected(false);
            btnOutrasDoencasInfancia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNenhumaDoencaInfanciaStateChanged

    private void btnSarampoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnSarampoStateChanged
        if (btnSarampo.isSelected()) {
            btnNenhumaDoencaInfancia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSarampoStateChanged

    private void btnCataporaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnCataporaStateChanged
        if (btnCatapora.isSelected()) {
            btnNenhumaDoencaInfancia.setSelected(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnCataporaStateChanged

    private void btnCaxumbaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnCaxumbaStateChanged
        if (btnCaxumba.isSelected()) {
            btnNenhumaDoencaInfancia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCaxumbaStateChanged

    private void btnRubeolaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnRubeolaStateChanged
        if (btnRubeola.isSelected()) {
            btnNenhumaDoencaInfancia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRubeolaStateChanged

    private void btnCoquelucheStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnCoquelucheStateChanged
        if (btnCoqueluche.isSelected()) {
            btnNenhumaDoencaInfancia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoquelucheStateChanged

    private void btnEscarlatinaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnEscarlatinaStateChanged
        if (btnEscarlatina.isSelected()) {
            btnNenhumaDoencaInfancia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscarlatinaStateChanged

    private void btnOutrasDoencasInfanciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnOutrasDoencasInfanciaStateChanged
        if (btnOutrasDoencasInfancia.isSelected()) {
            txtQuaisDoencasInfancia.setVisible(true);
            lblTituloQuaisDoencasInfancia.setVisible(true);
            btnNenhumaDoencaInfancia.setSelected(false);
        } else {
            txtQuaisDoencasInfancia.setVisible(false);
            lblTituloQuaisDoencasInfancia.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOutrasDoencasInfanciaStateChanged

    private void btnEscarlatinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscarlatinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscarlatinaActionPerformed

    private void btnPerdaPesoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnPerdaPesoStateChanged
        if (btnPerdaPeso.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerdaPesoStateChanged

    private void btnAlzheimerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnAlzheimerStateChanged
        if (btnAlzheimer.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlzheimerStateChanged

    private void btnDemenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnDemenciaStateChanged
        if (btnDemencia.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDemenciaStateChanged

    private void btnTremorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnTremorStateChanged
        if (btnTremor.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnTremorStateChanged

    private void btnDiabetesMellitusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnDiabetesMellitusStateChanged
        if (btnDiabetesMellitus.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnDiabetesMellitusStateChanged

    private void btnHipertensaoArterialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnHipertensaoArterialStateChanged
        if (btnHipertensaoArterial.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHipertensaoArterialStateChanged

    private void btnPerdaVisualStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnPerdaVisualStateChanged
        if (btnPerdaVisual.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnPerdaVisualStateChanged

    private void btnPerdaAuditivaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnPerdaAuditivaStateChanged
        if (btnPerdaAuditiva.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnPerdaAuditivaStateChanged

    private void btnAvcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnAvcStateChanged
        if (btnAvc.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnAvcStateChanged

    private void btnOsteomeliteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnOsteomeliteStateChanged
        if (btnOsteomelite.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnOsteomeliteStateChanged

    private void btnHipercolesterolemiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnHipercolesterolemiaStateChanged
        if (btnHipercolesterolemia.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnHipercolesterolemiaStateChanged

    private void btnIncontinenciaFecalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnIncontinenciaFecalStateChanged
        if (btnIncontinenciaFecal.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnIncontinenciaFecalStateChanged

    private void btnTuberculoseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnTuberculoseStateChanged
        if (btnTuberculose.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnTuberculoseStateChanged

    private void btnHepatiteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnHepatiteStateChanged
        if (btnHepatite.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHepatiteStateChanged

    private void btnAsmaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnAsmaStateChanged
        if (btnAsma.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnAsmaStateChanged

    private void btnGotaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnGotaStateChanged
        if (btnGota.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnGotaStateChanged

    private void btnParkinsonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnParkinsonStateChanged
        if (btnParkinson.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParkinsonStateChanged

    private void btnIncontinenciaUrinariaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnIncontinenciaUrinariaStateChanged
        if (btnIncontinenciaUrinaria.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnIncontinenciaUrinariaStateChanged

    private void btnEfisemaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnEfisemaStateChanged
        if (btnEfisema.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEfisemaStateChanged

    private void btnAnsiedadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnAnsiedadeStateChanged
        if (btnAnsiedade.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnAnsiedadeStateChanged

    private void btnDepressaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnDepressaoStateChanged
        if (btnDepressao.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnDepressaoStateChanged

    private void btnArtriteReumatoideStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnArtriteReumatoideStateChanged
        if (btnArtriteReumatoide.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnArtriteReumatoideStateChanged

    private void btnSifilisStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnSifilisStateChanged
        if (btnSifilis.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnSifilisStateChanged

    private void btnDisturbioComportamentalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnDisturbioComportamentalStateChanged
        if (btnDisturbioComportamental.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisturbioComportamentalStateChanged

    private void btnArtroseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnArtroseStateChanged
        if (btnArtrose.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnArtroseStateChanged

    private void btnEsquecimentoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnEsquecimentoStateChanged
        if (btnEsquecimento.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnEsquecimentoStateChanged

    private void btnTonteiraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnTonteiraStateChanged
        if (btnTonteira.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnTonteiraStateChanged

    private void btnDoencaChagasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnDoencaChagasStateChanged
        if (btnDoencaChagas.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnDoencaChagasStateChanged

    private void btnSindromePanicoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnSindromePanicoStateChanged
        if (btnSindromePanico.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnSindromePanicoStateChanged

    private void btnOutrasDoencasPreviasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnOutrasDoencasPreviasStateChanged
        if (btnOutrasDoencasPrevias.isSelected()) {
            btnNenhumaDoencaPrevia.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnOutrasDoencasPreviasStateChanged

    private void btnNenhumaDoencaPreviaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnNenhumaDoencaPreviaStateChanged
        if (btnNenhumaDoencaPrevia.isSelected()) {
            btnPerdaPeso.setSelected(false);
            btnAlzheimer.setSelected(false);
            btnDemencia.setSelected(false);
            btnTremor.setSelected(false);
            btnDiabetesMellitus.setSelected(false);
            btnHipertensaoArterial.setSelected(false);
            btnPerdaVisual.setSelected(false);
            btnPerdaAuditiva.setSelected(false);
            btnAvc.setSelected(false);
            btnOsteomelite.setSelected(false);
            btnHipercolesterolemia.setSelected(false);
            btnIncontinenciaFecal.setSelected(false);
            btnTuberculose.setSelected(false);
            btnHepatite.setSelected(false);
            btnAsma.setSelected(false);
            btnGota.setSelected(false);
            btnParkinson.setSelected(false);
            btnIncontinenciaUrinaria.setSelected(false);
            btnEfisema.setSelected(false);
            btnAnsiedade.setSelected(false);
            btnDepressao.setSelected(false);
            btnArtriteReumatoide.setSelected(false);
            btnSifilis.setSelected(false);
            btnDisturbioComportamental.setSelected(false);
            btnArtrose.setSelected(false);
            btnEsquecimento.setSelected(false);
            btnTonteira.setSelected(false);
            btnDoencaChagas.setSelected(false);
            btnSindromePanico.setSelected(false);
            btnOutrasDoencasPrevias.setSelected(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnNenhumaDoencaPreviaStateChanged

    private void btnNenhumaCirurgiaPreviaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnNenhumaCirurgiaPreviaStateChanged
        if (btnNenhumaCirurgiaPrevia.isSelected()) {
            lblCausaCirurgia.setVisible(false);
            txtCausaCirurgia.setVisible(false);
            lblDataCirurgia.setVisible(false);
            txtDataCirurgia.setVisible(false);
            lblLocalCirurgia.setVisible(false);
            txtLocalCirurgia.setVisible(false);
        } else {
            lblCausaCirurgia.setVisible(true);
            txtCausaCirurgia.setVisible(true);
            lblDataCirurgia.setVisible(true);
            txtDataCirurgia.setVisible(true);
            lblLocalCirurgia.setVisible(true);
            txtLocalCirurgia.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNenhumaCirurgiaPreviaStateChanged

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        AnamneseJF.setIdPessoa(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (AnamneseJF.getIdPessoa() > 0) {

            float peso = (float) spnPeso.getValue();
            float altura = (float) spnAltura.getValue();
            String tabagista = "";
            String etilista = "";
            LocalDate dataTabagista;
            String tipoTabagista = txtTipoTabagismo.getText();
            LocalDate dataEtilista;
            String tipoEtilista = "";
            String doencaInf = "";
            String doencaPre = "";
            String causaCirurgia = "";
            LocalDate dataCirurgia;
            String localCirurgia;
            if (altura > 0 && peso > 0) {
                /////Tabagismo
                if (btnSimTabagista.isSelected()) {
                    tabagista = btnSimTabagista.getText();
                    try {
                        dataTabagista = LocalDate.parse(txtDataTabagista.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
                        tipoTabagista = txtTipoTabagismo.getText();
                        if (tipoTabagista.isBlank()) {
                            lblSaida.setText("Tipo de tabagismo inválido");
                            return;
                        }
                    } catch (DateTimeParseException e) {
                        lblSaida.setText("Data do tabagismo inválida");
                        return;
                    }
                } else if (btnNaoTabagista.isSelected()) {
                    tabagista = btnNaoTabagista.getText();
                    try {
                        dataTabagista = LocalDate.parse(txtDataTabagista.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
                        tipoTabagista = txtTipoTabagismo.getText();
                        if (tipoTabagista.isBlank()) {
                            lblSaida.setText("Tipo de tabagismo inválido");
                            return;
                        }
                    } catch (DateTimeParseException e) {
                        lblSaida.setText("Data do tabagismo inválida");
                        return;
                    }
                } else if (btnNuncaTabagista.isSelected()) {
                    tabagista = btnNuncaTabagista.getText();
                }
                ////Etilismo
                if (btnEtilistaSim.isSelected()) {
                    etilista = btnEtilistaSim.getText();
                    try {
                        dataEtilista = LocalDate.parse(txtDataEtilista.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
                        tipoEtilista = txtTipoEtilista.getText();
                        if (tipoEtilista.isBlank()) {
                            lblSaida.setText("Tipo de etilismo inválido");
                            return;
                        }
                    } catch (DateTimeParseException e) {
                        lblSaida.setText("Data do etilismo inválida");
                        return;
                    }
                } else if (btnEtilistaNao.isSelected()) {
                    etilista = btnEtilistaNao.getText();
                    try {
                        dataEtilista = LocalDate.parse(txtDataEtilista.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
                        tipoEtilista = txtTipoEtilista.getText();
                        if (tipoEtilista.isBlank()) {
                            lblSaida.setText("Tipo de etilismo inválido");
                            return;
                        }
                    } catch (DateTimeParseException e) {
                        lblSaida.setText("Data do etilismo inválida");
                        return;
                    }
                } else if (btnEtilistaNunca.isSelected()) {
                    etilista = btnEtilistaNunca.getText();
                }
                //Doenças da infância
                if (btnSarampo.isSelected()) {
                    doencaInf += btnSarampo.getText() + ", ";
                }
                if (btnCatapora.isSelected()) {
                    doencaInf += btnCatapora.getText() + ", ";
                }
                if (btnCaxumba.isSelected()) {
                    doencaInf += btnCaxumba.getText() + ", ";
                }
                if (btnRubeola.isSelected()) {
                    doencaInf += btnRubeola.getText() + ", ";
                }
                if (btnCoqueluche.isSelected()) {
                    doencaInf += btnCoqueluche.getText() + ", ";
                }
                if (btnEscarlatina.isSelected()) {
                    doencaInf += btnEscarlatina.getText() + ", ";
                }
                if (btnNenhumaDoencaInfancia.isSelected()) {
                    doencaInf += btnNenhumaDoencaInfancia.getText() + ", ";
                }
                if (btnOutrasDoencasInfancia.isSelected()) {
                    doencaInf += txtQuaisDoencasInfancia.getText() + ", ";
                }
                //Doeças prévias 
                if (btnPerdaPeso.isSelected()) {
                    doencaPre += btnPerdaPeso.getText() + ", ";
                }
                if (btnAlzheimer.isSelected()) {
                    doencaPre += btnAlzheimer.getText() + ", ";
                }
                if (btnDemencia.isSelected()) {
                    doencaPre += btnDemencia.getText() + ", ";
                }
                if (btnTremor.isSelected()) {
                    doencaPre += btnTremor.getText() + ", ";
                }
                if (btnDiabetesMellitus.isSelected()) {
                    doencaPre += btnDiabetesMellitus.getText() + ", ";
                }
                if (btnHipertensaoArterial.isSelected()) {
                    doencaPre += btnHipertensaoArterial.getText() + ", ";
                }
                if (btnPerdaVisual.isSelected()) {
                    doencaPre += btnPerdaVisual.getText() + ", ";
                }
                if (btnAvc.isSelected()) {
                    doencaPre += btnAvc.getText() + ", ";
                }
                if (btnOsteomelite.isSelected()) {
                    doencaPre += btnOsteomelite.getText() + ", ";
                }
                if (btnHipercolesterolemia.isSelected()) {
                    doencaPre += btnHipercolesterolemia.getText() + ", ";
                }
                if (btnIncontinenciaFecal.isSelected()) {
                    doencaPre += btnIncontinenciaFecal.getText() + ", ";
                }
                if (btnTuberculose.isSelected()) {
                    doencaPre += btnTuberculose.getText() + ", ";
                }
                if (btnHepatite.isSelected()) {
                    doencaPre += btnHepatite.getText() + ", ";
                }
                if (btnAsma.isSelected()) {
                    doencaPre += btnAsma.getText() + ", ";
                }
                if (btnGota.isSelected()) {
                    doencaPre += btnGota.getText() + ", ";
                }
                if (btnParkinson.isSelected()) {
                    doencaPre += btnParkinson.getText() + ", ";
                }
                if (btnIncontinenciaUrinaria.isSelected()) {
                    doencaPre += btnIncontinenciaUrinaria.getText() + ", ";
                }
                if (btnEfisema.isSelected()) {
                    doencaPre += btnEfisema.getText() + ", ";
                }
                if (btnAnsiedade.isSelected()) {
                    doencaPre += btnAnsiedade.getText() + ", ";
                }
                if (btnDepressao.isSelected()) {
                    doencaPre += btnDepressao.getText() + ", ";
                }
                if (btnArtriteReumatoide.isSelected()) {
                    doencaPre += btnArtriteReumatoide.getText() + ", ";
                }
                if (btnSifilis.isSelected()) {
                    doencaPre += btnSifilis.getText() + ", ";
                }
                if (btnDisturbioComportamental.isSelected()) {
                    doencaPre += btnDisturbioComportamental.getText() + ", ";
                }
                if (btnArtrose.isSelected()) {
                    doencaPre += btnArtrose.getText() + ", ";
                }
                if (btnEsquecimento.isSelected()) {
                    doencaPre += btnEsquecimento.getText() + ", ";
                }
                if (btnTonteira.isSelected()) {
                    doencaPre += btnTonteira.getText() + ", ";
                }
                if (btnDoencaChagas.isSelected()) {
                    doencaPre += btnDoencaChagas.getText() + ", ";
                }
                if (btnSindromePanico.isSelected()) {
                    doencaPre += btnSindromePanico.getText() + ", ";
                }
                if (btnNenhumaDoencaPrevia.isSelected()) {
                    doencaPre += btnNenhumaDoencaPrevia.getText() + ", ";
                }
                if (btnOutrasDoencasPrevias.isSelected()) {
                    doencaPre += txtQuaisDoencasPrevias.getText() + ", ";
                }
                //Cirurgia Prévia
                if (!btnNenhumaCirurgiaPrevia.isSelected()) {
                    localCirurgia = txtLocalCirurgia.getText();
                    causaCirurgia = txtCausaCirurgia.getText();
                    try {
                        dataCirurgia = LocalDate.parse(txtDataCirurgia.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
                        if (localCirurgia.isBlank() || causaCirurgia.isBlank()) {
                            lblSaida.setText("Campos em branco em cirurgia");
                            return;
                        }
                    } catch (DateTimeParseException e) {
                        lblSaida.setText("Data da cirurgia inválida");
                        return;
                    }
                }
                //Anamnese no banco
                if (!tabagista.isBlank() && !etilista.isBlank() && !doencaInf.isBlank() && !doencaPre.isBlank()) {
                    doencaInf = doencaInf.substring(0, doencaInf.length() - 2);//Retira os últimos caracteres a mais.
                    doencaPre = doencaPre.substring(0, doencaPre.length() - 2);//Retira os últimos caracteres a mais.
                    Anamnese a1 = new Anamnese(AnamneseJF.getIdPessoa(), peso, altura, tabagista, etilista, doencaInf, doencaPre);
                    if (!a1.verificarAnamnese()) {
                        a1.cadastrarAnamnese();
                        a1 = Anamnese.buscarAnamneseIdPessoa(AnamneseJF.getIdPessoa());
                        ////Cadastrar tabela tabagismo
                        if (!btnNuncaTabagista.isSelected()) {
                            try {
                                dataTabagista = LocalDate.parse(txtDataTabagista.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
                                tipoTabagista = txtTipoTabagismo.getText();
                                if (tipoTabagista.isBlank()) {
                                    lblSaida.setText("Campo em branco em tabagismo");
                                    return;
                                }
                                Tabagismo t1 = new Tabagismo(a1.getIdAnamnese(), dataTabagista, tipoTabagista);
                                t1.cadastrarTabagismo();
                            } catch (DateTimeParseException e) {
                                lblSaida.setText("Data do tabagismo inválida");
                                return;
                            }
                        }
                        //////Cadastrar Etilismo
                        if (!btnEtilistaNunca.isSelected()) {
                            try {
                                dataEtilista = LocalDate.parse(txtDataEtilista.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
                                tipoEtilista = txtTipoEtilista.getText();
                                if (tipoEtilista.isBlank()) {
                                    lblSaida.setText("Campo em branco em etilismo");
                                    return;
                                }
                                Etilista e1 = new Etilista(a1.getIdAnamnese(), dataEtilista, tipoEtilista);
                                e1.cadastrarEtilista();
                            } catch (DateTimeParseException e) {
                                lblSaida.setText("Data do etilista inválida");
                                return;
                            }
                        }
                        //////////Cadastrar Cirurgia
                        if (!btnNenhumaCirurgiaPrevia.isSelected()) {
                            try {
                                dataCirurgia = LocalDate.parse(txtDataCirurgia.getText(), DateTimeFormatter.ofPattern("dd/MM/uuuu"));
                                localCirurgia = txtLocalCirurgia.getText();
                                causaCirurgia = txtCausaCirurgia.getText();
                                if (localCirurgia.isBlank() || causaCirurgia.isBlank()) {
                                    lblSaida.setText("Campo em branco em cirurgia");
                                    return;
                                }
                                Cirurgia c1 = new Cirurgia(a1.getIdAnamnese(), causaCirurgia, dataCirurgia, localCirurgia);
                                c1.cadastrarCirurgia();
                            } catch (DateTimeParseException e) {
                                lblSaida.setText("Data do etilista inválida");
                                return;
                            }
                        }
                        AnamneseJF.setIdPessoa(0);
                        lblSaida.setText("Anamnese cadastrada com sucesso");
                    } else {
                        lblSaida.setText("Esse paciente já possui anamnese");
                    }

                } else {
                    lblSaida.setText("Campos em branco");
                }

            } else {
                lblSaida.setText("Valores de altura ou peso inválidos");
            }
        } else {
            lblSaida.setText("Busque um paciente antes de cadastrar a anamnese");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAlzheimer;
    private javax.swing.JRadioButton btnAnsiedade;
    private javax.swing.JRadioButton btnArtriteReumatoide;
    private javax.swing.JRadioButton btnArtrose;
    private javax.swing.JRadioButton btnAsma;
    private javax.swing.JRadioButton btnAvc;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JRadioButton btnCatapora;
    private javax.swing.JRadioButton btnCaxumba;
    private javax.swing.JRadioButton btnCoqueluche;
    private javax.swing.JRadioButton btnDemencia;
    private javax.swing.JRadioButton btnDepressao;
    private javax.swing.JRadioButton btnDiabetesMellitus;
    private javax.swing.JRadioButton btnDisturbioComportamental;
    private javax.swing.JRadioButton btnDoencaChagas;
    private javax.swing.JRadioButton btnEfisema;
    private javax.swing.JRadioButton btnEscarlatina;
    private javax.swing.JRadioButton btnEsquecimento;
    private javax.swing.JRadioButton btnEtilistaNao;
    private javax.swing.JRadioButton btnEtilistaNunca;
    private javax.swing.JRadioButton btnEtilistaSim;
    private javax.swing.JRadioButton btnGota;
    private javax.swing.ButtonGroup btnGroupEtilista;
    private javax.swing.ButtonGroup btnGroupExEtilista;
    private javax.swing.ButtonGroup btnGroupExTabagista;
    private javax.swing.ButtonGroup btnGroupTabagista;
    private javax.swing.JRadioButton btnHepatite;
    private javax.swing.JRadioButton btnHipercolesterolemia;
    private javax.swing.JRadioButton btnHipertensaoArterial;
    private javax.swing.JRadioButton btnIncontinenciaFecal;
    private javax.swing.JRadioButton btnIncontinenciaUrinaria;
    private javax.swing.JButton btnInserir;
    private javax.swing.JRadioButton btnNaoTabagista;
    private javax.swing.JRadioButton btnNenhumaCirurgiaPrevia;
    private javax.swing.JRadioButton btnNenhumaDoencaInfancia;
    private javax.swing.JRadioButton btnNenhumaDoencaPrevia;
    private javax.swing.JRadioButton btnNuncaTabagista;
    private javax.swing.JRadioButton btnOsteomelite;
    private javax.swing.JRadioButton btnOutrasDoencasInfancia;
    private javax.swing.JRadioButton btnOutrasDoencasPrevias;
    private javax.swing.JRadioButton btnParkinson;
    private javax.swing.JRadioButton btnPerdaAuditiva;
    private javax.swing.JRadioButton btnPerdaPeso;
    private javax.swing.JRadioButton btnPerdaVisual;
    private javax.swing.JRadioButton btnRubeola;
    private javax.swing.JRadioButton btnSarampo;
    private javax.swing.JRadioButton btnSifilis;
    private javax.swing.JRadioButton btnSimTabagista;
    private javax.swing.JRadioButton btnSindromePanico;
    private javax.swing.JRadioButton btnTonteira;
    private javax.swing.JRadioButton btnTremor;
    private javax.swing.JRadioButton btnTuberculose;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblBuscaCpf;
    private javax.swing.JLabel lblCausaCirurgia;
    private javax.swing.JLabel lblDataCirurgia;
    private javax.swing.JLabel lblDataTabajista;
    private javax.swing.JLabel lblEtilistaData;
    private javax.swing.JLabel lblEtilistaTitulo;
    private javax.swing.JLabel lblImcTitulo;
    private javax.swing.JLabel lblLocalCirurgia;
    private javax.swing.JLabel lblPacienteTitulo;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblTabagistaTitulo;
    private javax.swing.JLabel lblTipoEtilista;
    private javax.swing.JLabel lblTipoTabagismo;
    private javax.swing.JLabel lblTituloCirurgiaPrevia;
    private javax.swing.JLabel lblTituloDoencasInfancia;
    private javax.swing.JLabel lblTituloDoencasPrevias;
    private javax.swing.JLabel lblTituloQuaisDoencasInfancia;
    private javax.swing.JLabel lblTituloQuaisDoencasPrevias;
    private javax.swing.JSpinner spnAltura;
    private javax.swing.JSpinner spnPeso;
    private javax.swing.JTextField txtCausaCirurgia;
    private javax.swing.JFormattedTextField txtCpfBusca;
    private javax.swing.JFormattedTextField txtDataCirurgia;
    private javax.swing.JFormattedTextField txtDataEtilista;
    private javax.swing.JFormattedTextField txtDataTabagista;
    private javax.swing.JTextField txtImc;
    private javax.swing.JTextField txtLocalCirurgia;
    private javax.swing.JTextField txtPacienteNome;
    private javax.swing.JTextField txtQuaisDoencasInfancia;
    private javax.swing.JTextField txtQuaisDoencasPrevias;
    private javax.swing.JTextField txtTipoEtilista;
    private javax.swing.JTextField txtTipoTabagismo;
    // End of variables declaration//GEN-END:variables
}
