package br.com.fisioterapia.jframe.cadastro;

import br.com.fisioterapia.database.pessoas.Fisioterapeuta;
import java.beans.PropertyVetoException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author aevan
 */
public class FisioterapeutaJF extends javax.swing.JInternalFrame {

    /**
     * Creates new form FisioterapeutaJF
     */
    public FisioterapeutaJF() {
        initComponents();
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException p) {
            lblSaida.setText("Ocorreu um erro ao maximizar o JInternal Frame");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lblCpf = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lblEndereco = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCrefito = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCrefito = new javax.swing.JFormattedTextField();
        lblSaida = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setForeground(java.awt.SystemColor.activeCaptionBorder);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Fisioterapeuta");
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        lblCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpf.setText("CPF");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(10, 51, 49, 24);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(130, 373, 120, 20);

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(10, 130, 67, 24);

        lblRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRg.setText("RG");
        getContentPane().add(lblRg);
        lblRg.setBounds(10, 86, 49, 24);

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(10, 170, 67, 24);

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("E-mail");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(10, 210, 67, 24);
        getContentPane().add(txtNome);
        txtNome.setBounds(69, 11, 248, 29);

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(80, 130, 360, 29);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(10, 11, 49, 24);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(80, 210, 248, 29);

        lblCrefito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCrefito.setText("CREFITO");
        getContentPane().add(lblCrefito);
        lblCrefito.setBounds(10, 250, 67, 24);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(64, 288, 248, 29);

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setText("Senha");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(20, 328, 38, 17);

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLogin.setText("Login");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(20, 290, 50, 17);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(62, 328, 244, 30);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(70, 50, 120, 30);

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AA.AAA.AAA-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtRg);
        txtRg.setBounds(70, 90, 120, 30);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(80, 170, 110, 30);

        try {
            txtCrefito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-**")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCrefito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCrefito);
        txtCrefito.setBounds(80, 250, 100, 30);
        getContentPane().add(lblSaida);
        lblSaida.setBounds(10, 400, 330, 20);

        getAccessibleContext().setAccessibleName("Fisioterapeuta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String endereco = txtEndereco.getText();
        String usuario = txtUsuario.getText();
        String senha = new String(txtSenha.getPassword());

        String rg1[] = txtRg.getText().split("-");
        String rg2[] = rg1[0].split("\\.");
        String rg = rg2[0] + rg2[1] + rg2[2] + rg1[1];

        String cpf1[] = txtCpf.getText().split("-");
        String cpf2[] = cpf1[0].split("\\.");
        String testeCpf = cpf2[0] + cpf2[1] + cpf2[2] + cpf1[1];
        long cpf;

        String telefone1[] = txtTelefone.getText().split("-");
        long telefone;

        String crefito1[] = txtCrefito.getText().split("-");
        String crefito = crefito1[0] + crefito1[1];

        if (!nome.isBlank() && !email.isBlank() && !endereco.isBlank() && !rg.isBlank() && !testeCpf.isBlank() && !telefone1[0].isBlank() && !telefone1[1].isBlank() && !crefito.isBlank() && !usuario.isBlank() && !senha.isBlank()) {
            cpf = Long.parseLong(testeCpf);

            String telefone2[] = telefone1[0].split(" ");
            String testeTelefone = telefone2[0] + telefone2[1] + telefone1[1];

            telefone = Long.parseLong(testeTelefone);

            Fisioterapeuta f1 = new Fisioterapeuta(crefito, usuario, senha, nome, cpf, rg, telefone, email, endereco);

            if (!f1.verificarCpf()) {
                if (!f1.verificarUsuario()) {
                    if (!f1.verificarCrefito()) {
                        f1.cadastrarPessoaFisioterapeuta();
                        f1.setCodPessoa(f1.buscarCodPessoa(cpf));
                        f1.cadastrarFisioterapeuta();
                        lblSaida.setText("Fisioterapeuta cadastrado com sucesso!!!");
                    } else {
                        lblSaida.setText("Crefito já cadastrado!!!");
                    }
                } else {
                    lblSaida.setText("Usuário já cadastrado!!!");
                }

            } else {
                lblSaida.setText("CPF já cadastrado!!!");
            }

        } else {
            lblSaida.setText("Campos em branco!!!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCrefito;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtCrefito;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
